conventional-changelog/commitlint

- package.json
- source/rules/scope-empty.js
- test/rules/scope-empty.js
*  add related regression tests
*  default to "never" keyword
*  correctly negate rule result and message for "always"
closes #10
> fix(rules): respect keyword setting for scope-empty

- source/library/ensure-enum.js
- source/rules/scope-enum.js
- test/rules/scope-empty.js
- test/rules/scope-enum.js
Disabled `empty-scope` along with defined scope-enum rule yields `scope-enum` errors when linting commits without scope
```js
{
"extends": ["angular"],
"rules": {
"scope-enum": [2, "always", ["api", "system"]]
}
}
```
```
❯ echo "fix: foo" | ./node_modules/.bin/conventional-changelog-lint
⧗   input: fix: foo
✖   scope must be one of [api, system] [scope-enum]
✖   found 1 problems, 0 warnings
```
Disabled `empty-scope` causes commits with empty scope to validate
```
❯ echo "fix: foo" | ./node_modules/.bin/conventional-changelog-lint
⧗   input: fix: foo
✔   found 0 problems, 0 warnings
```
> fix: allow empty scopes in scope-enum check

- source/rules/index.js
Hi, `subject-min-length` rule in `conventional-changelog-lint@1.1.8` has been missing since [80cd7cc](https://github.com/marionebl/conventional-changelog-lint/commit/80cd7cc312f83dcad5bd99dd698ee2d11bd18e7b#diff-2c0890a5b10b691838ef2e4068896167).
[source/rules/index.js](https://github.com/marionebl/conventional-changelog-lint/blob/89afc0116d10dd65b8b8c68ea4d1254171862ed6/source/rules/index.js) should export [source/rules/subject-min-length.js](https://github.com/marionebl/conventional-changelog-lint/blob/89afc0116d10dd65b8b8c68ea4d1254171862ed6/source/rules/subject-min-length.js) :smiley:  
my-sharable-config/index.js:
```javascript
rules: {
'subject-min-length': [
1,
'always',
0
]
}
};
```
Stack trace:
```sh
/home/user/project/node_modules/conventional-changelog-lint/di …
```
> fix(rules): export subject-min-length rule

- source/index.js
- source/library/parse.js
- source/rules/footer-leading-blank.js
- test/rules/footer-leading-blank.js
- test/rules/scope-empty.js
- test/rules/scope-enum.js
* footer-leading-blank commonly produced false positives for empty footers
* closes #13
> fix: prevent false positives for footer-leading-blank

- @commitlint/cli/readme.md
- @commitlint/config-angular/readme.md
- @commitlint/config-lerna-scopes/readme.md
- @commitlint/config-patternplate/readme.md
- @commitlint/prompt-cli/package.json
- @commitlint/prompt-cli/readme.md
- @commitlint/prompt/package.json
- @commitlint/prompt/readme.md
- README.md
- docs/README.md
- docs/concepts-shareable-config.md
- docs/guides-ci-setup.md
- docs/guides-local-setup.md
- docs/guides-upgrade.md
- docs/guides-use-prompt.md
- raised in #47
- motivates #48
> docs: use new commitlint.config.js name in all examples

- README.md
Fixes the error:
```bash
➜ npm install --save-dev @commitlint/{angular,cli}
npm ERR! code E404
npm ERR! 404 Not Found: @commitlint/angular@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/okonet/.npm/_logs/2017-07-27T09_27_59_210Z-debug.log
```
> docs: Fix installation instructions

- @commitlint/core/src/rules/index.js
- @commitlint/core/src/rules/signed-off-by.js
- @commitlint/core/src/rules/signed-off-by.test.js
- docs/reference-rules.md
Added a new rule to allow for commit messages to be validated for the `Signed-off-by:` syntax as added when doing `git commit --signoff`.
I **think** I've changed everything required for this, but please shout up if I've missed something.
> feat(core): add Signed-off-by rule

- docs/README.md
Added a missing `.md` extension to the guides-local-setup link in the docs README
> Fixes the guides-local-setup link in the docs README

- @commitlint/core/src/library/is-ignored.js
- @commitlint/core/src/library/is-ignored.test.js
**Edit** by @marionebl:
* Add support for version commits with footers, e.g. as produced by `--sign-off` or Gerrit.
* Add relevant test cases
> feat(core): ignore version commits with footers

- @commitlint/cli/cli.js
- @commitlint/core/src/read.js
- @commitlint/core/src/read.test.js
- docs/reference-api.md
- docs/reference-cli.md
I took the liberty to tackle #40 because I was suffering from the same problem.
> feat: edit flag now accepts the path to the commit file

- docs/guides-ci-setup.md
I think the line is redundant, because it is already present in the shell script.
> Remove redundant line

- @commitlint/core/fixtures/basic/commitlint.config.js
- @commitlint/core/package.json
- @commitlint/core/src/load.js
- @commitlint/core/src/load.serial-test.js
- yarn.lock
Fixes a bug with `@commitlint/prompt-cli` where config was not loaded due to `options.cwd` defaulting to `''` previously.
> fix(core): default to process.cwd #100

- @commitlint/core/src/rules/index.js
- @commitlint/core/src/rules/references-empty.js
- @commitlint/core/src/rules/references-empty.test.js
- docs/reference-rules.md
* allow to test for presence of references
* common use case is checking of an issue id was given
* will require parserOpts for most projects
* issue references from commit header are omitted via angular preset
* Supersedes #76 
* Closes #95
> feat: add references-empty rule

- @commitlint/core/src/library/ensure-case.js
- @commitlint/core/src/library/ensure-case.test.js
- @commitlint/core/src/rules/scope-case.test.js
- docs/reference-rules.md
- yarn.lock
1. Add standard-case rule
2. Add test cases
> feat(core): add sentence-case to ensure-case

- @commitlint/core/fixtures/global-install/commitlint.config.js
- @commitlint/core/fixtures/missing-install/commitlint.config.js
- @commitlint/core/package.json
- @commitlint/core/src/library/resolve-extends.js
- @commitlint/core/src/library/resolve-extends.test.js
- @packages/test/src/git.js
- yarn.lock
> fix(core): fall back to globally installed config if available

- CHANGELOG.md
Provides a clickable link to the change in the angular repo that removes the `chore` keyword.
> docs(changelog): add hyperlink to change that removes "chore"

- README.md
Add a link to the readme to the contribution guide.
I did not found the contribution guide at first, so I added a link to the readme so nobody else has to search for it longer than he should 🤓
> docs: add contribution guide link to readme

- README.md
Add table of contents to readme.
To find things faster you're looking for, a table of contents can help.
I wanted to get a quick overview of the related content in the readme, so I thought a table of contents could help.
> docs: add contents list to readme

- @commitlint/config-conventional/README.md
Fix to correct package name (maybe typo):
`@commitlint/config-conventions` => `@commitlint/config-conventional`
Motivation to correct package documentation.
N/A
N/A
> docs: fix to correct package name (`config-conventional`)

- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
The commit adds a new special parser for the `edit` flag for Windows,
so that `$GIT_PARAMS` can be read from the command-line
commitlint on Windows doesn't work when `$GIT_PARAMS` are
specified in the package.json file.
#103 
```js
extends: ["@commitlint/config-conventional"]
};
```
```js
// package.json
{
...
"scripts": {
"commitmsg": "commitlint -e $GIT_PARAMS"
}
}
```
**Edit**:
> fix(cli): add support for GIT_PARAMS on windows. Closes #103

- @commitlint/prompt/src/settings.js
Didn't include this in my latest PR since it was supposedly going away,
but since both `config-conventional` and conventionalcommits.org still have it,
at the very least fix it so it's not the only one that appears without a description
in the prompt help.
> feat(prompt): help description for chore

- README.md
Added a section under 'getting started'.  
The basic setup is now available in a code block.
The setup was hard to find. IMHO this essential example should be shown in the readme.
> docs: added setup instructions to readme

- @commitlint/core/src/library/is-ignored.js
- @commitlint/core/src/library/is-ignored.test.js
Added `chore: vx.x.x` to the list of ignores.
Commitlint was failing to validate the commit produced by `standard-version`.
See #198 
```sh
echo "chore: v1.0.0" | commitlint # passes
echo "chore: 1.0.0" | commitlint # passes
echo "chore(release): v1.0.0" | commitlint # passes
echo "chore(release): 1.0.0" | commitlint # passes
```
Added the inputs above to the `is-ignored` tests.
> fix: fix npm semver commits with type chore not being ignored

- @commitlint/cli/fixtures/issue-prefixes/commitlint.config.js
- @commitlint/cli/fixtures/parser-preset/commitlint.config.js
- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
- @commitlint/core/src/lint.js
- @commitlint/core/src/lint.test.js
- @commitlint/core/src/load.js
- @commitlint/core/src/load.test.js
- @commitlint/parse/README.md
- @commitlint/parse/src/index.test.js
- @commitlint/resolve-extends/src/index.js
- @commitlint/rules/src/references-empty.test.js
> fix: pick up parser preset correctly

- @commitlint/core/src/lint.js
- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
> fix: ignore branch merges with newlines

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
Still having some issues with merge commits. Seems to be caused by merge commits occasionally having more than one newline character.
> fix: ignore branch merges with multiple newlines

- .github/CONTRIBUTING.md
When clicking the original links on GitHub, I am taken to a 404 page. By using absolute GitHub URLs, clicking Happiness and conventional-changelog will navigate to the expected webpages.
Was curious about contributing to this codebase and noticed this issue when I clicked the XO link.
N/A
Clicking the links in the GitHub markdown preview takes me to the expected pages.
> docs: use absolute URLs in CONTRIBUTING.md

- @commitlint/parse/src/index.js
- @commitlint/parse/src/index.test.js
Changes `parse` to default to `conventional-changelog-angular` for empty objects. Previously only `falsy` values triggered the default.
* Closes #262 
* New unit test
> fix(parse): default to angular preset for empty parserOpts

- README.md
Instead of `--save` use `--save-dev` to align with other examples in the `README.md`.  
If this was intended then just ignore this.
Alignment with other things only. Not an issue.
> docs: update teaser for core packages

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
This PR is related to issue #60 and [this comment](https://github.com/marionebl/commitlint/issues/60#issuecomment-369888823).
This adds two types of Bitbucket merge commits to the ignore list, which are generated by Bitbucket itself. It should allow all Bitbucket users to use the default message without the linter going berserk on these messages.
We at [Peakfijn](https://peakfijn.nl) definitely want to use this tool. But since we are using Bitbucket all of our projects raises false positives on the default merge messages.
The following commands should now pass without failing.
```sh
$ echo "Merged in feature/facebook-friends-sync (pull request #8)" | commitlint
$ echo "Merged develop into feature/component-form-select-card" | commitlint
```
I added these exact messages to the test file …
> feat: add bitbucket merge commits to ignore list

- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
- @commitlint/lint/src/index.js
- @commitlint/lint/src/index.test.js
- yarn.lock
Print the full commit message when the input message is invalid.
On `@commitlint/cli` when a commit message has validation errors, it prints the full commit message, returned by the lint function, otherwise, it prints just the commit header, just like before.
On `@commitlint/lint`, the return object returns the input parsed (useful for delete comments on editors like vim).
Currently, when using the CLI, if the message is invalid we lose all its content (using a custom message in VIM mode), which might be a little frustrating when we a have a long commit body, so it would be nice if we show the previous message after the linting errors.
Closes #222
1. `git commit`
2. Input commit message:
```
foo
Lorem ipsum dolor sit amet consectetur adipisicing elit.
```
Output is:
```js
⧗   input:
foo …
```
> feat: print commit message when the message is invalid

- README.md
Fix installation syntax for Windows.
Curly braces syntax [**doesn't work**](https://stackoverflow.com/a/38876970/5951529) for Windows-specific terminals.
```node
D:\SashaDemoRepositories\SashaCommitlint>npm install --save-dev @commitlint/{config-conventional,cli}
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@commitlint\{config-conventional,cli}" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SashaChernykh\AppData\Roaming\npm-cache\_logs\2018-04-10T13_23_19_766Z-debug.log
```
```node
D:\SashaDemoRepositories\SashaCommitlint>npm install --save-dev @commitlint/config-conventional @commitlint/cli
+ @commitlint/config-conventional@6.1.3
+ @commitlint/cli@6.1.3
added 170 packages from 61 contributors in 34.977s …
```
> fix(platform): windows installation

- docs/reference-cli.md
Referencing this PR: https://github.com/marionebl/commitlint/pull/261 , I updated the docs to include `--config / -g` flag for passing a custom configuration.
http://marionebl.github.io/commitlint/#/reference-cli
Added `--config, -g` to docs.
Greater visibility for cli options
```js
// path/to/my/custom/config/commitlint.config.js 
extends: ['@commitlint/config-conventional'],
// Disabling scope-case rule
rules: {
'scope-case': [0],
}
};
```
```sh
echo "your commit message here" | commitlint --config path/to/my/custom/config/commitlint.config.js # pass
```
https://github.com/marionebl/commitlint/pull/261
> docs(cli): added --config flag

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
[Github deployments](https://developer.github.com/v3/repos/deployments/) have an `auto_merge` parameter that "attempts to automatically merge the default branch into the requested ref, if it is behind the default branch" . 
The automatic merge commit generated by a Github Deployment looks like `Auto-merge [branch] into [branch]` and this was failing commitlint.
See [this](https://github.com/jcarroll2007/commitlint/blob/fix/add-auto-merge-wildcard/%40commitlint/is-ignored/src/index.test.js#L107) line for the tests.
> feat(is-ignored): added wildcard ignore for automatic merge commits

- @commitlint/config-lerna-scopes/readme.md
Fix typo in config-lerna-scopes readme file.
> docs(readme): fix typo

- @commitlint/ensure/src/case.js
- @commitlint/ensure/src/case.test.js
fixes #317
In single, double and back quests uses own names (i.e. name of packages, technologies and etc, example `Less`, `SCSS` and etc) and it is break commit linting
```js
module.exports = { extends: ["@commitlint/config-conventional"] };
```
```sh
echo "fix(docs): use `WordPress` instead `wordpress`" | commitlint # fails
```
write tests
> fix: support any case in single, double and back quotes

- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
- README.md
- docs/guides-local-setup.md
- docs/guides-upgrade.md
- docs/reference-cli.md
- package.json
Add an argument `-E | --env` to the cli which accepts the name of an environment variable to be used for the path to the commit message file.
This also fixes some minor typos in the docs.
I haven't removed the `$GIT_PARAMS` handling as that should be a breaking change. However, it could be removed in a later version.
Fixes #319. 
In the newest/upcoming versions of Husky ([1.0.0-rc.1](https://github.com/typicode/husky/blob/dev/CHANGELOG.md#100-rc1)), the environment variable husky uses is renamed to `HUSKY_GIT_PARAMS` from `GIT_PARAMS`.
This means that the cross platform support for husky built into the CLI doesn't work for this and subsequent releases.
This implements the second fix suggested in https://github.com/marionebl/commitlint/issues/319#issue-318569827.
The alternative to this …
> fix(cli): add environment variable cli flag

- @commitlint/config-angular/index.js
- @commitlint/config-conventional/index.js
Change `subject-case` rule on config-conventional and config-angular to non-negating rules.
Many scripts, i.e. Han, Devanagari, are not cased. Thus `ensureCase` will always return true for texts written in these scripts on any case rules.
Negating case rules will cause `test: 你好` as invalid since they are conformed to any case rules.
For definition of cased, see http://unicode.org/reports/tr44/#Cased
```js
};
```
```sh
```
Deprecate the use of `never` on case rules as
- there exists many scripts not cased
- Better warnings on casing policy when commit messages fails. Think about comparing
> subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
with
> …
> fix(rules): do not negate case rules

- @commitlint/config-conventional/README.md
The thing that `commitlint` enforces is properly called "conventional commits" rather than "convention commits". So, update a reference in the readme to use the term more correctly.
Improves readability. Notice a glitch in docs, fix the glitch in docs.
[Viewed the resulting Markdown as rendered by GitHub](https://github.com/apetro/commitlint/blob/692101166cf7777c599d0a3e9680bc6143ef2f1b/%40commitlint/config-conventional/README.md).
> docs(readme): "conventional" not "convention"

- README.md
> [docs] Fix Husky setup instructions

- README.md
Fixes documentation to reflect a correct Husky setup, as per @escapedcat's review
```js
};
```
```sh
```
> [docs] Fix Husky hook example

- @commitlint/lint/src/index.js
- @commitlint/lint/src/index.test.js
Fixes #313
I've updated the tests which asserts if `Found invalid rule names: foo, bar` is returned.
It's actually a minor refactor I think?
> refactor(lint): use invalid instead of missing for unknown rules

- README.md
In the README.md, the comments didn't line up with the commands. The commands are installing and setting up `config-conventional` but the comments mention `angular`. I updated the comments to align with the commands.
> docs: Change "angular" to "conventional"

- README.md
applying for commitlint.io to be added to related projects
commitlint.io is a project based on commitlint package.
commitlint.io provide another way to lint commit message for team members 
with a simple user interface and no need for any installation.
> docs: add commitlint.io to related projects

- @commitlint/rules/src/footer-leading-blank.js
- @commitlint/rules/src/footer-leading-blank.test.js
Fixes #292 
See [comment #426696523](https://github.com/marionebl/commitlint/issues/292#issuecomment-426696523)
```sh
echo 'docs(plugins): fix old docs\n\nConfig -> Plugins\n\ncloses #21' | npx commitlint -x '@commitlint/config-conventional'
```
```sh
echo 'feat: mail is now created by the supplied template function\n\nInstead of supplying all mail fields in the queue the information from the queue is given to a template function. This helps to prevent creating open mail servers that can be abused for spam. Also refactored the tests to a more traditional style.\n\nBREAKING CHANGE: The `template` option is required.' | npx commitlint -x '@commitlint/config-conventional'
```
> fix(rules): include possible body offset in footer leading blank

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
If the merge commit has more characters after the new line it was not be ignored by commitlint.
I had to do uncomfortable actions in order to avoid it.
For instance, this message was not be ignored:
```
Merge branch 'master' of https://github.com/xxx/xxx
#
#	.git/MERGE_HEAD
#
#
#
#	modified:   config/locale/en.po
#	modified:   config/locale/es.po
#	modified:   config/locale/messages.pot
#
```
I created a test
Bug fix (non-breaking change which fixes an issue)
> Ignoring merge commits with newline and extra text

- @commitlint/cli/fixtures/custom-formatter/formatters/custom.js
- @commitlint/cli/package.json
- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
- @commitlint/load/fixtures/formatter-local-module/commitlint.config.js
- @commitlint/load/fixtures/formatter-local-module/formatters/custom.js
- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
Fixes #463 
See issue #463 
See issue #463 
See issue #463
> fix(cli): improve format module resolving

- @commitlint/format/README.md
The new formatters feature introduced the [new report-structure](https://github.com/marionebl/commitlint/issues/377#issuecomment-419658320). This structure is created [within the CLI](https://github.com/marionebl/commitlint/blob/master/%40commitlint/cli/src/cli.js#L152-L167) and [passed to the formatter](https://github.com/marionebl/commitlint/blob/master/%40commitlint/cli/src/cli.js#L169) to produce a nice string.
I'd recon if people want to create their own formatter, they probably checkout the default `@commitlint/format`.
> docs(format): update example code with new report structure

- README.md
First reported by #471 
Always use the safest way to link, especially on external links.
> docs: use https for all external links in readme

- @commitlint/prompt/package.json
- package.json
This is a dependency security upgrade, complementary to #473. 
I did a manual security audit, with `npm audit`, and found 2 issues. While one of them isn't included in any commitlint package, I think it's best to still upgrade because of the security level (critical). The other issue is a minor one, also related to old Lodash, through commitizen.
<details><summary><b><i>root package</i></b></summary>
<p>
This one is related to `docsify-cli` using the insecure `open` library, this has been patched and refactored by `opn`. This change is [done here](https://github.com/docsifyjs/docsify-cli/commit/5df389962a0eb69ac02701b297b77b2fbb85ec28).
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection …
```
> fix: solve dependency security issues

- docs/guides-local-setup.md
I updated the docs to reflect the husky's official docs about how to setup hooks
> docs: update local setup guide with latest version of husky

- @commitlint/format/src/index.js
- @commitlint/format/src/index.test.js
- README.md
Should fix #471  
New output message looks liek this:
```sh
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
(Need help? -> https://github.com/marionebl/commitlint#what-is-commitlint)
```
Updated tests for `format`
I think master is still broken for now. Need to check this in another PR.
> docs: point first-time users to docs

- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
This adds `HUSKY_GIT_PARAMS` fallback to the existing `GIT_PARAMS` deprecation handling, as [described in their docs](https://github.com/typicode/husky#upgrading-from-014).
> Note, I've created two solutions for this problem. This is one, and the [other one is to remove (and later reimplement)](https://github.com/marionebl/commitlint/pull/499). Please pick one, I'll close the other.
> Edit, I prefer this one since it's now backward compatible.
> refactor(cli): add fallback with husky git params to deprecation handling

- @commitlint/cli/src/cli.js
Use console.log() instead of process.stdout.write() will avoid potential output truncation on macOS.
Replace usage of `process.stdout.write()` with `console.log()`.
I noticed this first when using `commitlint` with `husky`:
I confirmed this wasn't a `husky`-specific issue by simply piping STDIN:
On macOS, if output is truncated--the `node` process quits before the STDOUT stream has ended--we will see a `%`.
I then confirmed this happens in `master`:
I went and looked for the message in the codebase, and found it was output via a call to `process.stdout.write()`, which was the likely culprit.
"Works on my machine":
I *could* write a test that asserts output isn't truncated, but I *couldn't* be sure that it wouldn't be flaky.
I couldn't find a reason why `process.stdout.write()` was used in …
> fix(cli): avoid truncated output on macOS

- @commitlint/ensure/src/index.test.js
- @commitlint/parse/package.json
- @commitlint/parse/src/index.js
- @commitlint/parse/src/index.test.js
- yarn.lock
Fixes #341, #399, #445 
BREAKING CHANGE
This potentially changes implicit commitlint behaviour users may
have relied on in earlier versions. Instead of falling back to the
builtin commit-parser defaults we now default all keys to
conventional-changelog-angular.
> fix: fall back to conventional commit-parser settings for missing keys

- @commitlint/cli/fixtures/default/commitlint.config.js
- @commitlint/cli/fixtures/husky/integration/commitlint.config.js
- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
- @commitlint/load/src/index.js
- @commitlint/load/src/index.serial-test.js
https://github.com/marionebl/commitlint/issues/107
Push *empty rules* error to commitlint results if no rules are found.
See: https://github.com/marionebl/commitlint/compare/master...escapedcat:feat/107_warn-on-empty-config?expand=1#diff-9ab1790ed00b7ca8fb5c7def7e9d2641R49
> feat: warn on empty config

- @commitlint/format/src/index.js
- @commitlint/format/src/index.test.js
addint new line to result to avoid messages after jumping into same line
https://github.com/marionebl/commitlint/issues/504
> fix(format): add new line to result

- @commitlint/lint/package.json
`lodash` is not a devDependency it is used at runtime.
> fix: move lodash to dependencies

- @commitlint/rules/src/header-case.js
- @commitlint/rules/src/header-case.test.js
- @commitlint/rules/src/header-full-stop.js
- @commitlint/rules/src/header-full-stop.test.js
- @commitlint/rules/src/index.js
- docs/reference-rules.md
This adds some extra, but missing, rules for header validation (#524). ~~Currently, there are some failing tests that need to be resolved first. But I think I might need some help/eyes to get that resolved.~~
This PR adds two new rules for the header; `header-case` and `header-full-stop`. Both are based on the already existing `subject-case` and `subject-full-stop`. Like requested in #524, this is useful when no types (and therefore no subject) are used in commits. 
In the issue, we also discussed the `header-empty`, but when using empty commit messages the parser will throw an error describing it "expects a raw commit". That makes the `header-empty` rule impossible.
Copied and edited the tests from the existing rules.
> Additional header rules (header-full-stop, header-case)

- @commitlint/read/src/index.js
Implements build-in support for linting the commits of _git sub modules_, which currently doesn't work because _sub modules_ don't have their own `.git` folder.
I updated the read module to determine if it is running from a git sub module or not and find the `COMMIT_EDITMSG` accordingly. It still uses `edit` argument if present, otherwise it looks at `.git` and checks whether it is a directory (if it is, look for the `COMMIT_EDITMSG` as before) or a file, in which case it reads the file to figure out where the `COMMIT_EDITMSG` can be found.
Comments on my implementation are welcome, I'm happy to change it if needed 🙂 
This change is required in order to support linting the commits of git sub modules.
Fixes #448
n/a
Tests are missing from this PR (at least for now) as it requires an update …
> feat: add support for git submodules

- @commitlint/cli/src/cli.js
- @commitlint/format/src/index.js
Avoid confusing duplication of result message if input and empty config.  
As discussed on slack.
Somewhere outside of the repo try:
```sh
echo "null " | node commitlint/@commitlint/cli/lib/cli.js --config commitlint/@commitlint/cli/fixtures/empty/commitlint.config.js
```
Result before:
```
⧗   input: null
✔   found 0 problems, 0 warnings
(Need help? -> https://github.com/marionebl/commitlint#what-is-commitlint)
✖   Please add rules to your `commitlint.config.js`
- Getting started guide: https://git.io/fpUzJ
- Example config: https://git.io/fpUzm [empty-rules]
✖   found 1 problems, 0 warnings
(Need help? -> https://github.com/marionebl/commitlint#what-is-commitlint)
```
Result after:
```
⧗   input:
null
✖   Please add rules to your `commitlint.config.js`
- Getting started guide: …
```
> fix(cli): cleanup message for input with no config

- @commitlint/cli/src/cli.js
[As discussed](https://github.com/marionebl/commitlint/issues/511#issuecomment-447680527) we can trim the empty input to invalidate an input which per default comes as `\n`.
#511
I need help here. [We have this test](https://github.com/marionebl/commitlint/blob/master/%40commitlint/cli/src/cli.test.js#L23) but I'm not sure what is being tested here. It worked before and still works...
> fix(cli): avoid linebreak in empty input

- @commitlint/ensure/src/case.js
- @commitlint/ensure/src/case.test.js
- @commitlint/rules/src/scope-case.js
Tried to narrow this down.
Using this scope `Modules\Graph` with the `pascal-case` rule fails.  
In `@commitlint/rules/src/scope-case.js`:  
`const r = ensure.case(scope, check.case);` this returns false for such case.
First I only try to add a test-case which would be suitable for this situation. If this is correct we could chech where a fix in `case.js` coudl be implemented.
Currently thsi test fails:
```
✖ case › true for Modules/Graph on pascal-case
```
> fix slash in scope #291

- @commitlint/ensure/src/case.js
- @commitlint/ensure/src/case.test.js
This changes the `sentence-case` rule to also accept upper-case characters in the first word, allowing the use of acronyms (e.g. "HTML", "JSX") and words which include upper-case characters (e.g. "JavaScript") at the beginning of a `sentence-case` input.
In a project, we're using ESLint style commit messages with set up `sentence-case` rule for the commit message subject. When authoring a commit message, the commit would be rejected from time to time due to use of a word with upper-case characters (or an acronym) at the beginning of the subject input.
According to sentence case inputs, I think the only `commitlint` "sentence-case" rule validation should be that the first character of the first word is capitalized. Related issue: #211.
```js …
```
> fix: `sentence-case` doesn't allow upper-case characters in first word

- @commitlint/rules/src/header-max-length.js
- @commitlint/rules/src/header-min-length.js
show current header length, when lint error.
> feat(rule-header-length): show current header length

- @commitlint/cli/README.md
- @commitlint/config-angular/README.md
- @commitlint/config-conventional/README.md
- @commitlint/config-lerna-scopes/readme.md
- @commitlint/config-patternplate/README.md
- @commitlint/format/README.md
- @commitlint/lint/README.md
- @commitlint/load/README.md
- @commitlint/prompt-cli/README.md
- @commitlint/prompt/README.md
- @commitlint/read/README.md
- README.md
> fix: all broken website references

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
I updated one of the regular expressions in `is-ignored`.
On bitbucket server's PR builds a commit is created with only the message "Automatic merge". This would cause commit linting to fail.
Updated the unit tests and ran locally with a commit of that message ("Automatic merge")
> Ignore bitbucket's automatic merge commit in PR builds

- @commitlint/ensure/src/case.js
- @commitlint/ensure/src/case.test.js
- @commitlint/rules/src/scope-case.js
- @commitlint/rules/src/scope-case.test.js
> fix: failing sentence-case for subjects with slashes

- @commitlint/resolve-extends/src/index.js
- @commitlint/resolve-extends/src/index.test.js
- docs/concepts-shareable-config.md
Adds a feature for question #596, and thus fixes #596. 
This change is based on [ESLint's method of scoped config packages](https://eslint.org/docs/developer-guide/shareable-configs#npm-scoped-modules).
```js
extends: ['@mycompany'] // @mycompany/commitlint-config
};
```
> See the documentation changes for more examples.
> feat(resolve-extends): accept short scoped package names in extends

- docs/concepts-commit-conventions.md
Fixes spelling of the word "for" in the docs:
https://conventional-changelog.github.io/commitlint/#/concepts-commit-conventions
This is a documentation-only change.
Thanks!
> docs: add missing character

- @commitlint/cli/src/cli.js
- @commitlint/lint/package.json
- @commitlint/lint/src/index.js
- @commitlint/lint/src/index.test.js
- @commitlint/load/fixtures/extends-plugins/commitlint.config.js
- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
- @commitlint/load/src/utils/loadPlugin.js
- @commitlint/load/src/utils/loadPlugin.test.js
- @commitlint/load/src/utils/pluginNaming.js
- docs/reference-plugins.md
This adds an eslint-esque plugin system to commitlint.
See #228 
See the new doc file in the PR.
Tests have been added to the following packages; `@commitlint/lint` and `@commitlint/load`
> feat: add support for plugins (#228)

- docs/_sidebar.md
- docs/reference-examples.md
Adding to a general example section to the docs to provide examples to typical usecases of commitlint configs.
This is just a draft. Happy to add more exmaples for the start.
> docs: add new example section #237

- @commitlint/is-ignored/src/index.js
- @commitlint/is-ignored/src/index.test.js
- @commitlint/lint/src/index.js
- @commitlint/lint/src/index.test.js
- @commitlint/load/src/index.js
- docs/reference-configuration.md
Adding in options to customise which messages can be ignored by commitlint.
For example, using this you could cause commitlint to fail for automated commit messages like ‘Merge upstream into branch’ or similar. It would also allow users to add their own custom ignores for automated systems.
In my company I have quite a few issues with these causing weird CI errors due to us only allowing fast-forward commits and it would be nice if Husky could tell us earlier.
> feat: config based is-ignored overrides

- @commitlint/parse/src/index.js
- @commitlint/parse/src/index.test.js
With a custom "headerCorrespondence" of two entries, commit message
subjects couldn't be parsed due to merge with the default (Angular).
For example, the following custom parser opts (ESLint style) wouldn't
work because "headerCorrespondence" is `['type', 'subject', 'subject']`
after the merge.
```js
{
headerPattern: /^(.*):\s(.*)$/,
headerCorrespondence: ['type', 'subject'],
}
```
See #594.
A corresponding test has been added.
> fix: don't merge array properties with custom opts

- @commitlint/cli/src/cli.js
- @commitlint/format/src/index.js
- @commitlint/format/src/index.test.js
- docs/reference-api.md
> refactor(format): expose format result with extra tests

- @commitlint/read/src/index.js
check the [readme](https://github.com/Rich-Harris/sander) from the sander repo:
> The same is true for methods like readFile - whereas in node you can do fs.readFile('path/to/file.txt', 'utf-8') if you want to specify utf-8 encoding, with sander the final argument should be a {encoding: 'utf-8'} object.
So we should fix the usage like this:
```js
const gitFile = await sander.readFile(dotgitPath, { encoding: 'utf-8' });
```
> fix: modify the parameters for the sander.readFile function (#448)

- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
`commitlint/load` uses `_.merge()` from lodash to combine properties from the "seed" config into the config module being loaded.  `merge()` mutates its first argument -- much like `Object.assign()` -- so a blank object can be prepended to the argument list to yield similar results while leaving the config module reference itself unmodified.
Mutation of the reference loaded (and cached) by the built-in `require()` can have very surprising effects on otherwise unrelated consumers of the config.
A test was added that compares serializations of the config module from before and after loading.
> fix: load and copy config module without mutation

- @commitlint/cli/fixtures/ignores/commitlint.config.js
- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
pass ignores from configuration to the linter
add `ignores` to the opts that get passed in to the lint function in @commitlint/cli
The `ignores` configuration property was not being used 
```js
rules: {
'type-enum': [2, 'always', ['type']],
'scope-enum': [2, 'always', ['scope']],
'subject-empty': [2, 'never']
},
ignores: [
commit => {
return commit.includes('WIP');
}
]
};
```
```sh
git commit -m "WIP"
```
Wrote 2 tests and tried committing with the ignores 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> fix: pass ignores from configuration in @commitlint/cli

- docs/README.md
- docs/_sidebar.md
- docs/guides-local-setup.md
- docs/guides-upgrade.md
- docs/reference-cli.md
> docs: add change for v8

- @commitlint/load/package.json
- yarn.lock
`@commitlint/load` now explicitly depends on `chalk`, previously relying on it being resolved as a dependency of one it's other dependencies.
- explicit dependencies ensure that modification of downstream dependencies (other `@commitlint` packages) don't introduce a breaking change to `@commitlint/load` (ex. if `chalk` is removed)
- this change is required to allow `commitlint` to work seamlessly with Yarn's PnP feature which enforces a strict dependency graph, as per the error below
```
Error: Package "@commitlint/load@8.0.0" (via "/home/meatwallace/.cache/yarn/v4/npm-@commitlint-load-8.0.0-5eacfb96635e9aeac8f1a0674491f29483348872/node_modules/@commitlint/load/lib/utils/loadPlugin.js") is trying to require the package "chalk" (via "chalk") without it being listed in its dependencies …
```
> fix(load): add explicit dependency on chalk

- @commitlint/top-level/index.d.ts
- @commitlint/top-level/index.js
- @commitlint/top-level/package.json
- @commitlint/top-level/src/index.ts
- @commitlint/top-level/tsconfig.json
- yarn.lock
Refactors `@commitlint/top-level` to TypeScript.
Part of #659.
> refactor(top-level): rewrite top level to typescript

- @commitlint/cli/fixtures/default-ignores-false/commitlint.config.js
- @commitlint/cli/fixtures/default-ignores-true/commitlint.config.js
- @commitlint/cli/fixtures/default-ignores-unset/commitlint.config.js
- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
pass defaultIgnores from configuration to the linter
Add `defaultIgnores` to the opts that get passed in to the lint function in @commitlint/cli
https://github.com/conventional-changelog/commitlint/issues/769 - CLI users can't opt out of default ignore rules.
```js
defaultIgnores: false,
rules: {
'subject-empty': [2, 'never']
}
};
```
```sh
echo "fixup!" | commitlint -V
⧗   input: fixup!
✖   subject may not be empty [subject-empty]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```
Wrote 2 tests
> fix: pass defaultIgnores from configuration in @commitlint/cli

- @commitlint/parse/package.json
- @commitlint/parse/src/index.test.ts
- @commitlint/parse/src/index.ts
- @commitlint/parse/src/types.ts
- @commitlint/parse/tsconfig.json
- tsconfig.json
- yarn.lock
> refactor: port parse to typescript

- @commitlint/cli/src/cli.js
- @commitlint/cli/src/cli.test.js
add customizable helpurl to cli
implements #781
I want to describe my customized commitlint configuration
> feat(cli): add helpurl flag

- @commitlint/resolve-extends/src/index.test.ts
- @commitlint/resolve-extends/src/index.ts
Extended `resolve-extends` to accept absolute file paths
When using Yarn PnP the items in the `extends` array is provided using `require.resolve`, which currently doesn't work as `resolve-extends` adds a preset to the path
```js
extends: [require.resolve('@commitlint/config-conventional')],
};
```
Copied the `ignores prefix for relative extends` test but using an absolute path instead
> feat(resolve-extends): accept absolute path in extends

- @commitlint/config-conventional/index.js
- @commitlint/config-conventional/package.json
- @commitlint/load/fixtures/parser-preset-factory/commitlint.config.js
- @commitlint/load/fixtures/parser-preset-factory/conventional-changelog-factory.js
- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
- yarn.lock
Related to PR #767 and discussion #658, but only includes the new parser. The configuration itself is not changed to avoid breaking changes.
The new short breaking change (`!`) is part of the specification now and should be implemented by the conventional configuration. It's been a long-awaited feature but required additional changes because the parser is wrapped in another promise/factory.
We might consider setting this parser as a fallback parser in the configuration. But that also changes the other configuration. I'm not sure if they updated their specifications and include the short breaking change.
```js
parserPreset: 'conventional-changelog-conventionalcommits',
};
```
```sh
echo "fix!: this fix is a breaking change" | commitlint
```
Added …
> feat(config-conventional): use parser with short breaking change support

- @commitlint/load/fixtures/recursive-parser-preset-factory/commitlint.config.js
- @commitlint/load/fixtures/recursive-parser-preset-factory/first-extended/index.js
- @commitlint/load/fixtures/recursive-parser-preset-factory/first-extended/second-extended/conventional-changelog-factory.js
- @commitlint/load/fixtures/recursive-parser-preset-factory/first-extended/second-extended/index.js
- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
Fixes #830 
See [this comment](https://github.com/conventional-changelog/commitlint/pull/821/files#r335709269)
> fix(load): resolve nested parser preset factories

- @commitlint/load/fixtures/parser-preset-conventional-without-factory/commitlint.config.js
- @commitlint/load/fixtures/parser-preset-conventional-without-factory/package.json
- @commitlint/load/src/index.js
- @commitlint/load/src/index.test.js
It's kind of weird how Node exits randomly, without proper warnings/errors, when a Promise is never resolved. This happened because the [older conventional-changelog-conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/blob/dadbbf8b1acbe4b3a8f345633bde3f4a4ad0bea4/packages/conventional-changelog-conventionalcommits/index.js) is used. This adds a fallback-support for when this happens instead of just quitting.
Added a special test for older parser presets that do not support the callback-factory.
> fix(load): add support for non-factory conventional parsers

- @alias/commitlint/cli.js
- @packages/utils/pkg-check.js
Fixes #887
Renovate opened a breaking PR to `@alias/commitlint`, which doesn't include any tests. Because of that it slipped our CI.
Not, I'll open a separate issue for that.
> fix(commitlint): use new read pkg syntax

- @commitlint/resolve-extends/package.json
Fix #874 `@types/node` as dev dependency.
Move `@types/node` from dependency to dev dependency list with an update to the latest ^12 version.
#874 as issue describes there is possibility to have colliding `@types/node` versions which cause an error in typescript build.
Created link to private repo and tested with typescript build.
> fix: #874 types node as dev dependency

- docs/reference-api.md
Add options parameter for load function.
Currently the doc shows the `seed` parameter, but doesn't show that there's also an `options` parameter available to load a custom file. This PR includes explanation and anexample use case for this parameter.
> docs: add options parameter for load function

- docs/guides-ci-setup.md
The original Travis config does not use high enough version of node so the commitlint does not work. Updated docs accordingly
See this for more info:
conventional-changelog#857 (comment)
> Add latest node version to travis config docs

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.js
- @packages/test/package.json
- @packages/test/src/fix.ts
- @packages/test/src/git.ts
- @packages/test/src/npm.ts
- jest.config.js
Migrates CI tests from ava to jest
While doing this refactor i took opportunity to validate why some of tests was not passing on windows machines and i added appropriate comments.
```js
// npm install is failing on windows machines
// The filename, directory name, or volume label syntax is incorrect.
// await execa('npm', ['install'], {cwd});
```
There is still one that is failing on windows machine:
- `should print full commit message when input from stdin fails`
its actually not an issue but test is failing:
```
Expected substring: "foo: bar·
Foo bar bizz buzz.·
Closes #123."
Received string:    "⧗   input: foo: bar
Foo bar bizz buzz.
Closes #123."
````
Unrelated
> test(cli): migrates tests from ava to jest

- @commitlint/cli/src/cli.test.js
Jest doesn't disable color outputs on some machines. That results in false positives in the CLI tests.
> test(cli): force plain text when comparing output

- @commitlint/prompt-cli/cli.test.js
- @commitlint/prompt-cli/package.json
- jest.config.js
migrate prompt-cli tests from ava to jest
`string-to-stream` is used only in tests, i moved it to dev dependencies
Unrelated
> test(prompt-cli): migrate ava tests to jest

- @commitlint/lint/package.json
- @commitlint/lint/src/index.test.js
- jest.config.js
migrate lint tests from ava to jest
Most of lint tests are ok, i found few "mistakes" in them and i fixed them (see comments)
Unrelated
> test(lint): migrate ava tests to jest

- @commitlint/cli/src/cli.test.js
- @commitlint/travis-cli/fixtures/commitlint.js
- @commitlint/travis-cli/fixtures/git.js
- @commitlint/travis-cli/package.json
- @commitlint/travis-cli/src/cli.js
- @commitlint/travis-cli/src/cli.test.js
- @packages/test/src/git.ts
- jest.config.js
- yarn.lock
migrate travis-cli tests from ava to jest
Most of travis-cli tests are commented out, i enabled / fixed some of them,
Should i update commented one to or should i remove it?
i will prefer that they can be enabled, but instead of cloning actual repo we could mock it up
Unrelated
> test(travis-cli): migrate tests from ava to jest

- @commitlint/cli/package.json
- @commitlint/lint/package.json
- @commitlint/read/package.json
- @commitlint/rules/package.json
- @commitlint/top-level/package.json
- @commitlint/travis-cli/package.json
- @packages/babel-preset-commitlint/package.json
- @packages/utils/package.json
- yarn.lock
Cleanup of no longer used dev dependencies and remove some invalid configurations for packages that are already ported to typescript
> chore: cleanup no longer used dev dependencies

- @commitlint/cli/package.json
- yarn.lock
add missing regenerator-runtime to dependencies
This fixes issue with executing cli.
New version is no yet released and its better to fix it now rather than after release
Manual test
> fix(cli): add missing regenerator-runtime to dependencies

- jest.config.js
Make sure that tests from deep folders are executed,
Currently test file located in `@commitlint\prompt\src\library\get-prompt.test.js` is not executed
Fix issue introduced in #786
> test: execute tests from all packages

- @commitlint/resolve-extends/src/index.test.ts
- @commitlint/resolve-extends/src/index.ts
> feat: add possibility to extend from string

- .circleci/config.yml
This change ensures that yarn.lock and other lock files are valid and do not change after install
Ci has to pass
> chore: use frozen lockfile to fail build if an update is needed

- package.json
`lint-staged` does add changes automatically now. Printed this warning 
```
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```
> chore: remove obsolete git add

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.js
- @commitlint/read/package.json
- @commitlint/read/src/get-edit-commit.ts
- @commitlint/read/src/get-edit-file-path.ts
- @commitlint/read/src/read.test.ts
- @packages/utils/package.json
- package.json
- yarn.lock
replace unmaintained [`sander`](https://github.com/Rich-Harris/sander) package with [`fs-extra`](https://github.com/jprichardson/node-fs-extra) #918
`sander` package seems unmaintained (not updated for 4 years) and `cli` is only place where is used.
`sander` has no type definition
`fs` promisify and utils.promisify is not supported in targeted node versions (this should be replaced if/when node 8 / 10 will is going to be targeted)
> refactor: replace unmaintained sander package with fs-extra

- @commitlint/cli/src/cli.test.js
- @commitlint/config-patternplate/index.js
- @commitlint/ensure/src/case.ts
- @commitlint/ensure/src/index.test.ts
- @commitlint/lint/src/index.js
- @commitlint/load/src/load.ts
- @commitlint/load/src/utils/load-parser-opts.ts
- @commitlint/load/src/utils/pick-config.ts
- @commitlint/parse/src/index.ts
- @commitlint/prompt/src/library/format.js
- @commitlint/prompt/src/library/get-forced-case-fn.js
- @commitlint/prompt/src/library/meta.js
- @commitlint/resolve-extends/src/index.ts
- @packages/utils/pkg-check.js
Import only required lodash functions, this format is recommended to reduce size of bundled package (in case if someone will use it in tooling)
Manual tests + unit tests
> chore: import only required lodash functions

- @commitlint/top-level/package.json
- @commitlint/top-level/src/index.ts
- yarn.lock
Remove invalid find-up type package
Remove `@types/find-up` package and remove unnecessary type augmentation as this package provides its own definition
see #710
> chore(find-up): remove invalid find-up type package

- @packages/test/src/npm.ts
This refactors the npm bootstrap utility to symlink dependencies installed into the mono repository instead of running a dedicated `npm install`. 
By doing so we should be able to keep test runtimes inside jest timeouts.
> test: speed up npm bootstrap

- @alias/commitlint-config-angular/package.json
- @alias/commitlint-config-lerna-scopes/package.json
- @alias/commitlint-config-patternplate/package.json
- @commitlint/config-angular-type-enum/package.json
- @commitlint/config-angular/package.json
- @commitlint/config-conventional/package.json
- @commitlint/config-lerna-scopes/package.json
- @commitlint/config-patternplate/package.json
- @commitlint/core/package.json
- @commitlint/ensure/package.json
- @commitlint/execute-rule/package.json
- @commitlint/format/package.json
- @commitlint/lint/package.json
- @commitlint/load/package.json
- @commitlint/message/package.json
- @commitlint/parse/package.json
- @commitlint/prompt-cli/package.json
- @commitlint/prompt/package.json
- @commitlint/read/package.json
- @commitlint/resolve-extends/package.json
- @commitlint/rules/package.json
- @commitlint/to-lines/package.json
- @commitlint/top-level/package.json
- @packages/utils/package.json
- package.json
- yarn.lock
align `package.json` across all packages
- remove all `exit 0` scripts, lerna no longer requires it
- remove lerna from devDependencies in `config-lerna-scopes` (follow up #950)
- align `repository.url` across packages (`git+`)
- add/remove type packages from packages (when used in context of package)
- remove `typescript`, `jest`, `ts-jest`, `@types/jest` from some packages as its inherited from root
- move `@types/node` to root as it was imported in some (not all packages) and should be available to all
- remove `@commitlint/parse` from some devDependencies as its not used in context of package
- `@types/resolve-from` is a stub and its not required as resolve-from has type definition
Manual validation and `eslint` with `eslint-plugin-import` executed locally
> chore: align all packages

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.js
- @commitlint/prompt-cli/cli.test.js
- @commitlint/prompt-cli/package.json
- yarn.lock
Drop `string-to-stream` package in favor of execa input option.
> test: update execa cli calls and remove string-to-stream

- @commitlint/config-conventional/index.js
This removes the "improvement" type from the list of allowed types in `@commitlint/config-conventional`.
Fixes https://github.com/conventional-changelog/commitlint/issues/898.
This reverts https://github.com/conventional-changelog/commitlint/pull/832.
Has not been tested (trivial change).
Tests and documentation were not changed in https://github.com/conventional-changelog/commitlint/pull/832.
> config-conventional: drop support for 'improvement' type

- @alias/commitlint/cli.js
- @alias/commitlint/cli.test.js
- @alias/commitlint/fixtures/default/commitlint.config.js
- @alias/commitlint/package.json
- jest.config.js
Simplify commitlint alias package and add tests for it
Remove unnecessary dependencies
> refactor(commitlint): simplify commitlint alias package

- package.json
Update lerna filter argument to reflect changes in api
In `lerna@v3.18.0`  filter `--include-filtered-dependencies` was renamed to `--include-dependencies` and currently it showing deprecation warning.
https://github.com/lerna/lerna/commit/f2c3a92fe41b6fdc5d11269f0f2c3e27761b4c85
> chore: rename lerna run include option

- @commitlint/cli/src/cli.js
- @commitlint/prompt/src/index.js
- @commitlint/prompt/src/input.js
- @packages/utils/pkg-check.js
remove unused eslint-disable comments
> chore: remove unused eslint-disable comments

- @commitlint/cli/package.json
- @commitlint/prompt/package.json
- @commitlint/read/package.json
- @commitlint/travis-cli/package.json
- jest.config.js
disable babel build for tests and simplify jest config
Reduce amount of changes required during migration of packages and simplifies addition of new tests for untested packages
> test: disable babel build for tests and simplify jest config

- @commitlint/ensure/src/index.test.ts
- @commitlint/lint/src/lint.ts
- @commitlint/rules/package.json
- @commitlint/rules/src/index.test.ts
- @packages/utils/package.json
- @packages/utils/pkg-check.js
use builtin Object.values instead of lodash/values
https://node.green/#ES2017-features-Object-static-methods-Object-values
> refactor: use builtin Object.values instead of lodash/values

- @commitlint/lint/package.json
- @commitlint/parse/fixtures/parser-preset/commitlint.config.js
- @commitlint/parse/fixtures/parser-preset/conventional-changelog-custom.js
- @commitlint/parse/package.json
- @commitlint/parse/src/index.test.ts
Remove unnecessary `import-from` package from parse tests
> test(parse): remove import-from package from tests

- @commitlint/lint/package.json
- @commitlint/lint/src/lint.ts
- @commitlint/load/src/load.ts
- @commitlint/prompt/src/library/format.js
- @commitlint/prompt/src/library/meta.js
use native Object.entries instead of lodash/toPairs
https://node.green/#ES2017-features-Object-static-methods-Object-entries
> refactor: use native Object.entries instead of lodash/toPairs

- @commitlint/parse/src/index.ts
- @commitlint/resolve-extends/src/index.ts
use native Array.isArray instead of lodash/isArray
in most places this got already migrated
https://node.green/#ES2015-built-ins-Proxy-Array-isArray-support
> refactor: use native Array.isArray instead of lodash/isArray

- @commitlint/load/src/utils/load-parser-opts.ts
use native String.startsWith instead of lodash/startsWith
https://node.green/#ES2015-built-ins-well-known-symbols-Symbol-match--String-prototype-startsWith
> refactor: use native String.startsWith instead of lodash/startsWith

- @commitlint/parse/package.json
- @commitlint/parse/src/index.ts
refactor parse to use object spread instead of `lodash/mergeWith`
defaultOpts and parserOpts must be object that contains array of string or literal values
```ts
export interface ParserOptions {
commentChar?: string;
headerCorrespondence?: string[];
headerPattern?: RegExp;
issuePrefixes?: string[];
mergeCorrespondence?: string[];
mergePattern?: RegExp;
noteKeywords?: string[];
revertCorrespondence?: string[];
revertPattern?: RegExp;
}
```
> refactor(parse): refactor parse to use object spread

- @commitlint/config-lerna-scopes/package.json
Fixes regression introduced by #936 and #406 
This rule supports both lerna@2 and lerna@3 versions and both cases are tested.
We should allow to use it with both of them and not warn users about missing `peerDependencies`
> fix(config-lerna-scopes): version range of lerna in peerDependencies

- @commitlint/travis-cli/src/cli.js
- @commitlint/travis-cli/src/cli.test.js
passdown travis-cli argument to @commitlint/cli
I want to have my config file in `./config/commitlint.config.js` and use in my script:
```json
{
"scripts": {
"lint:commit": "commitlint -e --config ./config/commitlint.config.js",
"lint:commit-travis": "commitlint-travis --config ./config/commitlint.config.js",
}
}
```
I haven't tested it, not sure how I should test it since it only works on Travis.
> fix(travis-cli): passdown argv to lint command

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.js
- @commitlint/load/package.json
- @commitlint/prompt-cli/cli.test.js
- @commitlint/prompt-cli/package.json
- @commitlint/travis-cli/package.json
- @packages/test/package.json
- @packages/utils/dep-check.js
- @packages/utils/package.json
- yarn.lock
> feat: upgrade execa to 3.4.0

- @commitlint/ensure/src/enum.test.ts
- @commitlint/is-ignored/src/is-ignored.test.ts
add missing test cases for ensure and is-ignored
> test: add missing test cases for ensure and is-ignored

- @commitlint/resolve-extends/src/index.ts
replace lodash/omit with spread
This syntax is not supported in targeted version of node but typescript does transpile it in ~same way as babel does
`lodash/omit` has huge performance impact on code and new syntax (transpiled) is up to 10 times faster
`omit` is also on roadmap to be removed from `lodash`
https://github.com/lodash/lodash/issues/2930
https://github.com/lodash/lodash/wiki/Roadmap
> refactor(resolve-extends): replace lodash/omit with spread

- @commitlint/prompt/src/library/get-forced-case-fn.js
Fix incorrect use of `when` in `getForcedCaseFn`
This package has no tests, and this issue was introduced while fixing #145 in 3a569a744a5d2af6a324f5b65adce6a346cd6073
manual test
> fix(prompt): incorrect use of when in getForcedCaseFn

- @commitlint/config-conventional/README.md
- @commitlint/config-conventional/index.js
- @commitlint/config-conventional/index.test.js
- @commitlint/config-conventional/package.json
- @commitlint/config-conventional/tsconfig.json
- Updated the config-conventional with footer/body max length
- Added tests to all the rules of config-conventional
- Updated the documentation of config-conventional to include missing rules
Related to: https://github.com/marionebl/commitlint/issues/303#issuecomment-418525320
```sh
echo "fix: some message
BREAKING CHANGE: footer with multiple lines
has a message that is way too long and will break the line rule 'line-max-length' by several characters" # fails
echo "fix: some message
BREAKING CHANGE: footer with multiple lines
but still no line is too long" # passes
```
```sh
echo "fix: some message
body with multiple lines
has a message that is way too long and will break the line rule 'line-max-length' by several characters" # fails
echo "fix: some message
body with multiple lines
but …
```
> feat(config-conventional): footer/body-max-line

- @commitlint/lint/src/lint.test.ts
- @commitlint/lint/src/lint.ts
bypass rules for completely empty commit messages (only of blank
lines/comments in message)
A commit consisting of only newlines and/or comments (i.e. an empty commit) will bypass any rules and return as a valid commit. Empty commit messages will cause git to abort the commit, unless the user has specified the `allow-empty-message` option. The code change in this pull request preserves all git behavior.
I believe this is just a fix, and _not_ a BREAKING CHANGE since it fixes an unintended error from occurring.
This change fixes #615 - it allows users to abort a commit without an error. A standard way to abort a commit once in the commit editor is to write an empty file, or a file consisting of only newlines and comments. Before this change, a user would encounter an error from the linter. …
> fix: ignore empty commit messages #615

- README.md
Add line of code how to install husky before usage them.
Better explain how to lint before commit and the required package to do this.
You can see the example usage in the `Getting Started` section of `README.md`.
It's just new text to the docs about the requirement of `Husky` to lint before commit.
> docs(readme): add install husky example

- docs/guides-ci-setup.md
Add docs about CircleCi configuration.
It would be great to supplement CI section with CircleCI config, not just Travis.
> docs: add note about CircleCI config

- @commitlint/prompt/README.md
Correct extend's name.
The installed extend is `@commitlint/angular` while the required extend is `@commitlint/conventional`.
> docs: update README.md

- .circleci/config.yml
Add node 13/14 as new testing jobs for circle-ci.
https://github.com/conventional-changelog/commitlint/pull/1936  
execa supports nodejs >=10, we should start moving our minimum version up.  
This is only a start to make this happen if wanted.
via circle-ci
> chore: add node 13/14 to circle-ci jobs

- @commitlint/load/src/load.test.ts
- @commitlint/load/src/load.ts
- @commitlint/types/src/load.ts
- docs/reference-plugins.md
Add support for local plugins inside `commitlint.config.js`
Sometimes you want to just add one custom rule without going throw the whole process of publishing an npm package. With this change, the developers can now send an object inside the `plugins` object, with the structure of a Plugin. Which I find super helpful because all the validations are inside only one place.
```js
rules: {
'hello-world-rule': [2, 'always'],
},
plugins: [
{
rules: {
'hello-world-rule': ({ subject }) => {
return [
subject.includes('Hello World'),
'Your subject should contain "Hello World" message',
];
},
},
},
],
};
```
```sh
echo "feat: random subject" | commitlint # fails
echo "feat: Hello World" | commitlint # passes
```
I tested locally.
> feat: add local plugins support

- @commitlint/rules/src/scope-case.ts
- @commitlint/rules/src/scope-enum.test.ts
- @commitlint/rules/src/scope-enum.ts
Implement support for having multiple scopes, e.g. `chore(foo,bar): baz` in `scope-enum` and enable `,` as a default separator in `scope-case`
`scope-case` already had support for using `/` and `\` and delimiters but this, and some issues have mentioned wanting it to be configurable or have it support `,`, ref #701.
This feature seems to have been wanted for a while, ref #75.
Other probably related issues: #318, #312, #307
```js
extends: ["@commitlint/config-conventional"],
rules: {
"scope-enum": [2, "always", ["main", "api", "web"]],
"scope-empty": [2, "never"]
}
};
```
```sh
echo "chore(api,web)" | commitlint #passes
echo "chore(api)" | commitlint #passes
echo "chore(unknown)" | commitlint #fails
echo "chore(web,unknown)" | commitlint #fails …
```
> feat: enable multiple scopes in scope-enum and scope-case rules

- @commitlint/config-lerna-scopes/fixtures/basic/lerna.json
- @commitlint/config-lerna-scopes/fixtures/basic/package.json
- @commitlint/config-lerna-scopes/fixtures/empty/lerna.json
- @commitlint/config-lerna-scopes/fixtures/empty/package.json
- @commitlint/config-lerna-scopes/fixtures/lerna-two/package.json
- @commitlint/config-lerna-scopes/fixtures/scoped/lerna.json
- @commitlint/config-lerna-scopes/fixtures/scoped/package.json
- lerna.json
- package.json
- yarn.lock
- switch config to reflect v3 usage
- use maypr versions for peerdeps
> chore: use non-fixed lerna version

- docs/reference-api.md
Suggesting a change that made my local setup work.
The documentation was out of sync with implementation. I suggest a small change that will fix the case for `@commitlint/read`
> Use read dafult export - requiring with CommonJS

- @commitlint/rules/src/signed-off-by.test.ts
- @commitlint/rules/src/signed-off-by.ts
Fix `signed-off-by` rule to ignore lines starting with `#`.
Lines starting with `#` are comments. They are added by `git commit` at the end of the commit message template to show which files are included in the commit, and removed from the actual commit message.
Before this change, the rule `signed-off-by` was rejecting pretty much all commit messages created by `git commit` from the command line.
With this change in place, the rule ignores commits and accepts commit message created by `git commit` from the command line.
Fixes #1809
**Configuration**
```js
rules: {
'signed-off-by': [2, 'always', 'Signed-off-by:']
}
};
```
**Command to run**
```sh
commitlint <<EOF
feat: foobar
Signed-off-by: Miroslav Bajtoš <mbajtoss@gmail.com>
EOF
```
**Actual …
> fix(rules): ignore comments in `signed-off-by`

- @commitlint/resolve-extends/src/index.test.ts
- @commitlint/resolve-extends/src/index.ts
Fixes #2069.
See #2069.
BREAKING CHANGE:
The order of the `extends` resolution is changed from right-to-left to left-to-right
See #2069.
See #2069.
> fix(resolve-extends): `extends` field should be resolved from left to right

- @commitlint/rules/src/body-full-stop.test.ts
- @commitlint/rules/src/body-full-stop.ts
- @commitlint/rules/src/index.ts
- @commitlint/types/src/rules.ts
- docs/reference-rules.md
This PR adds a `body-full-stop` rule.
Fixes #2143.
```js
rules: {
'body-full-stop': [2, 'always', '.'],
}
};
```
```js
echo "test: subject\n\nbody." | commitlint # passes
echo "test: test: subject\n\nbody" | commitlint # fails
```
```js
rules: {
'body-full-stop': [2, 'never', '.'],
}
};
```
```js
echo "test: subject\n\nbody." | commitlint # fails
echo "test: test: subject\n\nbody" | commitlint # passes
```
Adding more tests.
I don't have any knowledge nor experience in Javascript/Typescript, but this only requires copy/pasting and adapting existing code, so here is my modest contribution. I cannot state for sure if all tests passed, I developped within the Docker container but got weird issues when …
> feat(rules): add body-full-stop rule

- docs/reference-community-projects.md
Plugin to use functions as rule value.
Add [commitlint plugin function rules](https://github.com/vidavidorra/commitlint-plugin-function-rules) as community project. 
@escapedcat As per your suggestion in https://github.com/conventional-changelog/commitlint/issues/1698#issuecomment-712533869. I've kept it in the same style as the `commitlint.io` project.
Add my project.
n/a
n/a
_Not actually a bug fix but docs update, so I guess this type 😉_
> docs: add vidavidorra/commitlint-plugin-function-rules project

- @commitlint/is-ignored/src/defaults.ts
- @commitlint/is-ignored/src/is-ignored.test.ts
Updated wildcard regular expressions in `@commitlint\is-ignored\src\defaults.ts`
The following Azure DevOps auto-generated merge commit message format is being considered an error:
- "Merged PR 123: Description here" (fails because it does not contain "in" or "into")
This auto-generated merge commit message format is being considered an error:
- "Merge remote-tracking branch" (fails because is has no whitespace at the end)
```sh
echo "Merge remote-tracking branch" | commitlint # passes
echo "Merged PR 123: Description here" | commitlint # passes
```
I have added tests to cover my changes.
> fix(is-ignored): ignore azure devops messages

- README.md
Hi,
i just added the husky v5 example. 
https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-
cheers
> add husky v5 example setup code for HUSKY_GIT_PARAMS

- @commitlint/cli/fixtures/help-url/commitlint.config.js
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/load/src/load.ts
- @commitlint/load/src/utils/pick-config.ts
- @commitlint/types/src/lint.ts
- @commitlint/types/src/load.ts
- docs/reference-api.md
- docs/reference-configuration.md
To allow this, `helpUrl` is added as an optional base configuration
property, and falls back to the original default URL if neither the CLI
flag nor config option is specified. The CLI option takes precedence
over the config object, if both are supplied.
It can make configuration a bit more DRY if one can use the commitlint
configuration object to specify a custom help URL vs. having wrapper
scripts and similar things to make every invocation of `commitlint` run
with `--help-url` specified.
```js
rules: {
'type-enum': [2, 'never', ['foo']]
},
helpUrl: 'https://www.example.com/foo'
};
```
```sh
echo "an invalid commit message" | commitlint # fails
⧗   input: an invalid commit message
✖   subject may not be empty [subject-empty]
✖   type may not be …
```
> feat(load): allow specifying helpUrl via config

- @packages/utils/package.json
- @packages/utils/pkg-check.js
- yarn.lock
Fix issues in utils package
Scripts from this package are no longer working, after changes done to test package.
`tmp` is no longer imported within `test` #960
Manual test on windows and linux machines
> fix(utils): update code to allow it to be executed

- @commitlint/config-lerna-scopes/fixtures/yarn/@packages/a/package.json
- @commitlint/config-lerna-scopes/fixtures/yarn/@packages/b/package.json
- @commitlint/config-lerna-scopes/fixtures/yarn/package.json
- @commitlint/config-lerna-scopes/index.js
- @commitlint/config-lerna-scopes/index.test.js
- @commitlint/config-lerna-scopes/package.json
- @commitlint/config-lerna-scopes/readme.md
- yarn.lock
Using _mostly_ the same logic present in the lerna config, add support for yarn workspaces. Can be used with and without lerna.
Some users, like me, often use yarn workspaces without lerna. This config would still be very useful to validate that the scopes match.
Using the same setup of a normal lerna repo, one can just remove the `lerna.json` file and adapt the `package.json` to include a `workspaces` config. With that in mind, I copied an existing lerna fixture and adapted it to yarn.
> feat(config-lerna-scopes): support yarn workspaces

- .eslintrc.js
- @alias/commitlint/package.json
- @commitlint/cli/package.json
- @commitlint/load/package.json
- @commitlint/parse/package.json
- @commitlint/prompt/package.json
- @commitlint/read/package.json
- @commitlint/types/package.json
- @commitlint/types/src/format.ts
- @packages/test-environment/package.json
- yarn.lock
enable import/no-extraneous-dependencies with some notes
This is not working on windows machines -  https://github.com/benmosher/eslint-plugin-import/issues/1650
and is not reporting all errors due to - https://github.com/benmosher/eslint-plugin-import/pull/1104
> test: enable import/no-extraneous-dependencies

- README.md
Changes "**the the** Angular convention" into "**the** Angular convention" in `README.md`.
There is a typo in `README.md`.
The fix is visible in the `What is commitlint` section of `README.md`.
This is a simple modification of the `README.md` file.
> docs(readme): fix typo 'the the' -> 'the'

- @commitlint/format/src/format.ts
- @commitlint/types/src/format.ts
Small tweak to ChalkColor type, to disallow invalid values
> fix(types): correct chalkColor type

- @commitlint/load/src/utils/load-plugin.test.ts
- @commitlint/types/src/load.ts
Use `Rule` instead of `Rule<unknown>` so plugin developers don't need to cast every non-default
rule's value to `Rule<unknown>`.
Fixes an issue where TypeScript plugin developers that specify rules with a type other than `Rule<unknown>` need to cast every rule value to `Rule<unknown>` to prevent errors like shown below.
Haven't made an issue for this as I'm creating this PR right away, but happy to do so and/or discuss further.
```
TS2322: Type 'BaseRule<FunctionRule, "either">' is not assignable to type 'BaseRule<unknown, "either">'.
```
Example usage in my plugin. Note that without this change you'd need to do `'function-rules/body-case': functionRule as Rule<unknown>,`
```ts
type FunctionRule = (
parsed: Commit,
when: RuleConfigCondition,
) => RuleOutcome | Promise<RuleOutcome>;
const …
```
> fix(load): use `Rule | AsyncRule | SyncRule` as rule value type in `Plugin`

- docs/reference-configuration.md
Show default`js` example in docs to avoid confusion.
> docs: show config example in ts and js #2232

- @commitlint/load/package.json
- @commitlint/load/src/load.test.ts
- @packages/test/src/npm.ts
- yarn.lock
expose helper function `installModules` to ease test time and timeouts on windows machines 
this change removes ~5sec from tests on my machine
constant timeout on windows during development
https://github.com/npm/npm/issues/21148
> test(load): use installModules instead of npm install

- docs/reference-cli.md
A trailing double quote was added to [./docs/reference-cli.md](./docs/reference-cli.md) when #2391 landed.
Removes trailing double quote `"`  [./docs/reference-cli.md](./docs/reference-cli.md) that landed with #2391.
Unnecessary double quote `"` in docs.
N/A
Viewed file in my fork: https://github.com/psyrendust/commitlint/blob/971c5195e06e5af7d5bf66b30f9931efbf5a9f0d/docs/reference-cli.md
> docs: remove double quote character added by #2391

- package.json
Do not trigger renovate checks for private internal packages
closes #2464, closes #2465
> chore: disable renovate for private unpublished packages

- README.md
This PR decodes `%40` to `@` that unnecessarily and inconsistently encoded in README.md.
> docs(readme): decode "%40" to "@" that unnecessarily encoded

- @commitlint/config-conventional/README.md
This PR sorts `type-enum` value in `@commitlint/config-conventional/README.md` to match the implementation.
> docs(readme): sort type-enum value in @commitlint/config-conventional/README.md

- docs/reference-configuration.md
Updating the docs to explain how to pass the configuration using the CL
Updating the docs to show to how to pass the configuration file using the CLI 
I have `commilint` with `husky` and I have `commitlint.config.js` on the root of my project. However, it was not picking it up. I changed it to `yarn commitlint --config commitlint.config.js --edit $1` and started picking it up properly. 
`.husky/commit-msg` 
```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
yarn commitlint --config commitlint.config.js --edit $1
```
`commitlint.config.js`
```js
extends: ["@commitlint/config-conventional"],
ignores: [(commitMessage) => commitMessage.includes("chore(release):")],
};
```
I tested this on two private projects, on GitLab and GitHub and locally.
> Updating reference of configuration 

- @commitlint/prompt/src/index.ts
- yarn.lock
Async Function type cannot be verified by commitizen's function check, modify to Function type.
issue: https://github.com/conventional-changelog/commitlint/issues/2486#issuecomment-791682272
> fix(prompt): modify the entry point to pass commitizen's function check

- docs/guides-local-setup.md
Fixed a shell substitution in the local setup guide where `$1` was being resolved instead of being put into the Husky hook.
Changed the `"` in the example to `'` to avoid shell substitutions.
As reported in https://github.com/conventional-changelog/commitlint/issues/2511, the `$1` was not being put into the hook properly (as the second example gave). This brings the two in line with each other.
This is for setting up Husky with the package.
```shell
$ yarn husky add .husky/commit-msg 'yarn commitlint --edit $1'
$ cat .husky/commit-msg
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
yarn commitlint --edit $1
$
```
Manually tested it in Bash.
I didn't update tests since this was documentation.
> docs: fixed shell substitutions in local setup guide

- docs/guides-ci-setup.md
- docs/guides-upgrade.md
> docs(guides): spelling and grammar fixes

- @commitlint/types/src/rules.ts
Fix `subject-full-stop` rule configuration type declaration
As described in the official website [here](https://commitlint.js.org/#/reference-rules?id=subject-full-stop), the `subject-full-stop` rule has a default value of `.` and its value is of type `string` (or `undefined`), which is missing in current type declaration of [rules.ts module](https://github.com/conventional-changelog/commitlint/blob/7767ca2/%40commitlint/types/src/rules.ts) and causes the TypeScript compiler to throw and error.
Wrong type declaration of configuration
Previously:
```ts
import type { QualifiedRules } from '@commitlint/types';
export function fullStopFilter(rule: QualifiedRules['subject-full-stop']): string {
const [level, applicable, ruleValue] = rule;
}
```
this would cause the error:
```txt
Property '2' …
```
> fix(rules): fix subject-full-stop rule config value type

- @commitlint/types/src/format.ts
The import was importing as default but is not exported as
default. Now the import is importing `* as` so you don't have to use
the tsconfig option `esModuleInterop`
When importing "@commitlint/config-conventional" into a typescript project you cannot compile it without setting `esModuleInterop` to true in you tsconfig you get the below error
```
node_modules/@commitlint/types/lib/format.d.ts:1:8 - error TS1259: Module '"src/node_modules/@commitlint/types/node_modules/chalk/index"' can only be default-imported using the 'esModuleInterop' flag
1 import chalk from 'chalk';
~~~~~
node_modules/@commitlint/types/node_modules/chalk/index.d.ts:415:1
415 export = chalk;
~~~~~~~~~~~~~~~
This module is declared with using 'export =', and can only be used with a default import when using the …
```
> fix(types): update chalk import

- @commitlint/types/src/rules.ts
Following #2534, the same other rule configuration key types are fixed.
Thanks!
> Fix rules configuration key types

- README.md
Fix `README.md` instructions regarding getting started with husky. Double quotes do not escape `$1` since it's a positional parameter.
Improve `README.md` documentation.
- [Repl.it](https://repl.it/@remarkablemark/Install-husky-hook-example)
- [YouTube](https://youtu.be/2J9VnYiZ_Ts)
https://github.com/remarkablemark/husky-commitlint-demo
> docs: fix husky add hook in 'Getting started'

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.ts
- yarn.lock
As in https://github.com/conventional-changelog/commitlint/pull/2552 the package `get-stdin` has moved to an ESM package. Reading their upgrade guide It looks like to use that you will need to move to an ESM package to use `get-stdin`. This removes the dependency and implements the one function in `cli.ts`.
This function is only being used once and only one function. I think this is a good way to go with minimal overhead. 
Let me know what you think
> Remove get-sdtin dependency

- @commitlint/format/README.md
- @commitlint/lint/README.md
- @commitlint/load/README.md
- @commitlint/read/README.md
- docs/reference-api.md
a walkaround for #2423, add `default` to all of the api module's `require` method in example code
> docs: correct way to get the default module in examples

- docs/guides-local-setup.md
This does not work 
```
npx commitlint --from HEAD~1 --to HEAD --verbose
```
and should be 
```
npx commitlint -- --from HEAD~1 --to HEAD --verbose
```
Improve documentation code snippet
Tested it in my own project while setting commitlint up
> docs(local-setup): fix npx command

- @commitlint/rules/package.json
- @commitlint/rules/src/index.ts
- @commitlint/rules/src/trailer-exists.test.ts
- @commitlint/rules/src/trailer-exists.ts
- @commitlint/types/src/rules.ts
- docs/reference-rules.md
This PR introduces the `trailer-exists` rule, based on #2567 but integrating the proposed features.
This new rule behaves similarly to the existing `signed-off-by` rule,
but introduces what would otherwise be breaking changes to the parser in
order to resolve some issues.
Rather than attempting to parse the trailers manually, this rule will
use Git's `interpret-trailers` subcommand to parse trailers according to
Git's rules. This allows us to properly detect all valid trailers, and
does not require that the trailer to search for be the last line of the
commit message (as is required by the `signed-off-by` rule).
One downside to this approach is that Git will not detect trailers if
they are grouped alongside other trailers with whitespace in the token
(e.g. `BREAKING CHANGE`). Projects …
> feat(rules): add `trailer-exists` rule

- @commitlint/cz-commitlint/README.md
Fix typo in commands of example usage
```js
```
```sh
```
> fix: typo in command

- @commitlint/config-angular/README.md
- @commitlint/config-angular/index.js
- @commitlint/config-angular/index.test.js
- @commitlint/config-angular/package.json
- @commitlint/config-conventional/index.test.js
- @commitlint/rules/src/index.ts
- @commitlint/rules/src/subject-exclamation-mark.test.ts
- @commitlint/rules/src/subject-exclamation-mark.ts
- docs/reference-rules.md
When using the conventional commit feature of an `!` in the commit
subject the angular config get really confused and gives some error
messages that do not relate to the issue due to the message failing at
the parse stage. This overrides the angular parser preset to add in
the exclamation mark then uses the new rule to give a better error
message.
The result is with the message "fix!: the fix" previously the error
message would be "subject may not be empty" now the error message is
"subject must not have an exclamation mark in the subject to identify
a breaking change". This message it more descriptive and will give the
user info they need to resolve the issue.
This also updates the docs to highlight the difference in angular and
conventional configs, and point them in the direction of …
> feat: add subject-exclamation-mark rule to improve error messages

- @commitlint/cli/fixtures/comment-char/commitlint.config.js
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
When running the cli and passing the `--edit` flag the comment char
was hard coded to a `#`. Even if there is a `commentChar` set in the
`parserOpts` the cli will override it with a `#`.
Now the cli will only set it to a `#` if its not already set in the
`parserOpts`
Fixes Issue: #2351
> fix(cli): remove hard coded comment char with linting `COMMIT_EDIT_MSG`

- README.md
- docs/guides-local-setup.md
> Add note about yarn v2 Plug'n'Play

- @commitlint/types/src/rules.ts
`CaseRuleConfig` now accepts `TargetCaseType | TargetCaseType[]`.
Fixes #2631.
Building a plugin + config package and running into the issue with all the `CaseRuleConfig` types don't except an array of cases. 
```ts
// index.ts (config package)
const config: UserConfig = {
extends: ['@commitlint/config-conventional'],
plugins: ['@bigcommerce/commitlint-plugin-jira'],
rules: {
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
'subject-case': [2, 'never', ['start-case', 'pascal-case']],
},
};
exports = config;
```
Installed and tested changes locally
> fix(types): adds TargetCaseType[] for CaseRuleConfig

- @commitlint/rules/src/body-case.ts
To keep the API consistent with all of the case rules the `body-case` rule now
accepts an array of cases like all of the other case types
Ref: #2631
Implement the `body-case` rule to accept an array of cases basically the same as the [`subject-case`](https://github.com/conventional-changelog/commitlint/blob/d9ad89a7e74055ef41b0e86b4ac3a763ff72b6ae/@commitlint/rules/src/subject-case.ts)
This is to go along with #2670 that adds the type for this, but is not currently implemented.
> feat(rules): allow body-case to accept an array of cases

- @commitlint/config-conventional/index.js
- @commitlint/cz-commitlint/src/Question.test.ts
- @commitlint/cz-commitlint/src/Question.ts
This PR adds a space after the title before the skip message and removes the double colon in the
`config-conventional` type of change prompt. For example (when using
`@commitlint/config-conventional`), the following would previously be printed:
```
Select the type of change that you're committing::  feat
What is the scope of this change (e.g. component or file name)(press enter to skip): (max 96 chars)
```
Now with this change:
```
Select the type of change that you're committing: feat
What is the scope of this change (e.g. component or file name) (press enter to skip): (max 96 chars)
```
> fix(cz-commitlint): fix minor formatting issues

- docs/reference-community-projects.md
Added a link to a community tool for working with Gitlab CI without throwing errors.
This addresses https://github.com/conventional-changelog/commitlint/issues/885#issuecomment-888001845 which references a problem when `commitlint` is first run on a Gitlab CI and blows up because it cannot read the SHA. After a number of discussions, I wrote a little utility to encapsulate the last "best" set of scripts to make it easy to work with Gitlab CI.
```sh
npx commitlint-gitlab-ci -x @commitlint/config-conventional
```
The documentation was just a copy of the link. The utility was manually tested on a number of Gitlab CI.
> docs: added commitlint-gitlab-ci in community docs

- README.md
- docs/_sidebar.md
- docs/guides-releases.md
After #2687 came up @AdeAttwood suggested to add something like this to our readme:  https://nodejs.org/en/about/releases/  
So at least we communicate a policy and be transparent about what we (at least try to) do.  
My understanding is we would try to port the the lodash issue (#2688) back to v8 to v12 and release patch releases but that would be it for now.  
After that we would [point to this table](https://github.com/conventional-changelog/commitlint/tree/docs/releases-eol#version-support-and-releaes) if something similiar happens again.
What do you think?
> docs: add releases EOL section

- @commitlint/load/fixtures/recursive-extends-ts/commitlint.config.ts
- @commitlint/load/fixtures/recursive-extends-ts/first-extended/index.ts
- @commitlint/load/fixtures/recursive-extends-ts/first-extended/second-extended/index.ts
- @commitlint/load/fixtures/recursive-extends-ts/types.ts
- @commitlint/load/package.json
- @commitlint/load/src/load.test.ts
- @commitlint/load/src/utils/load-config.ts
- @commitlint/types/src/load.ts
- @commitlint/types/src/prompt.ts
- yarn.lock
Add ts format config support. 
Reference to [cosmiconfig loader](https://github.com/davidtheclark/cosmiconfig#loaders) document, add [@endemolshinegroup/cosmiconfig-typescript-loader](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader) to load the ts config according to a higher priority than the js config.
#2652
> feat(load): add cosmiconfig typescript loader

- docs/guides-local-setup.md
With the extra `--` in the command line, commitlint checked my entire git history.  Removing the `--` makes it check just the latest commit.
I ran both the old and new commands.  The old one wasn't good, and the new one was :)
> docs: correct the "Test simple usage" command

- docs/guides-ci-setup.md
docs: add codemagic-ci info
docs: add codemagic-ci info
```js
```
```sh
```
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
> docs: add codemagic-ci info

- @commitlint/parse/package.json
- yarn.lock
Ensure that installing `@commitlint/parse` will not accidentally depend
on an insecure version of `conventional-commits-parser` by requiring
v3.22.2 or above as a dependency.
Dependabot gave us a security advisory but did not provide any means of
rectifying it. I used `yarn why` to determine that `trim-off-newlines`
is depended upon by `conventional-commits-parser`, which is depended
upon by `@commitlint/parse`, so this seemed like a good place to require
a higher version of the library to quell the security warning.
n/a
Ran `yarn test` locally to ensure that it didn't break anything obvious.
> Enforce Secure Version of `conventional-commits-parser`

- @commitlint/load/package.json
- yarn.lock
Added a direct dependency on typescript to the `@commitlint/load` package in order to satisfy the peer requirement from `@endemolshinegroup/cosmiconfig-typescript-loader`. 
this could be removed if EndemolShineGroup/cosmiconfig-typescript-loader#147 is satisfied upstream
fixes #2779 
this does not impact usage, only installation
N/A
> Added a direct dependency on typescript to the `@commitlint/load` package

- @commitlint/format/src/format.test.ts
- @commitlint/format/src/format.ts
- @commitlint/load/fixtures/help-url/commitlint.config.js
- @commitlint/load/src/load.test.ts
- @commitlint/load/src/load.ts
- @commitlint/resolve-extends/src/index.ts
- README.md
- docs/guides-local-setup.md
- Allow helpUrl to be extended from from shareable config
- This also hides `Get help:` string if helpUrl is not configured.   
- update docs containing deprecated `--no-install` npx option
It is not possible to customize the helpUrl via shareable config. It has to be added into individual repos'. This allows shareable config to have helpUrl.
```js
// commitlint.config.js <-- shareable config
helpUrl: 'https://commitlint.js.org/'
};
```
```sh
```
- Added test cases for changes made.
- created a new project and using yarn link to installed the local changes for testing
> feat: extend helpUrl from shareable config

- @commitlint/cli/package.json
- @commitlint/config-patternplate/package.json
- @commitlint/ensure/package.json
- @commitlint/format/package.json
- @commitlint/lint/package.json
- @commitlint/load/package.json
- @commitlint/prompt/package.json
- @commitlint/resolve-extends/package.json
- @commitlint/rules/package.json
- @packages/utils/package.json
CVE-2021-23337 in package lodash https://nvd.nist.gov/vuln/detail/CVE-2021-23337
This will probably need to be backported to v9 and v10 I will look at them soon. I will also look into the other versions
Ref: 2687
> chore: update lodash to 4.17.21

- @commitlint/load/src/load.test.ts
- @commitlint/types/src/rules.ts
Allow Typescript projects to provide a function returning a Promise of a rule configuration
Fixes the type signature of [QualifiedRuleConfig](https://github.com/conventional-changelog/commitlint/blob/master/@commitlint/types/src/rules.ts) that didn't match the current implementation and adds tests to check on all  allowed types of rule configuration.
Fixing mismatched types and allow correct use of asynchronous rule configurations without requiring additional custom plugins.
```ts
// commitlint.config.ts
import type { UserConfig } from '@commitlint/types';
const config: Userconfig = {
rules: {
'scope-enum': () => Promise.resolve([1, 'always', ['one', 'two', 'three']])
}
};
export default config
```
```sh
echo "feat(one): message" | commitlint # passes
```
Additional tests have been added …
> fix(types): fix signature of QualifiedRuleConfig for async configurations (#2868)

- @commitlint/cz-commitlint/src/SectionHeader.test.ts
- @commitlint/cz-commitlint/src/SectionHeader.ts
- @commitlint/cz-commitlint/src/store/defaultPromptConfigs.ts
- @commitlint/cz-commitlint/src/store/prompts.test.ts
- @commitlint/types/src/prompt.ts
- docs/reference-prompt.md
support select scope with radio list by setting disableMultipleScopes
add config option `prompt.settings.disableMultipleScopes`, give a option to disable multiple scopes, select scope with a radio list.
Ref: #2896 
It's convenient to select by enter when only a single one scope is required.
```js
prompt: {
settings: {
disableMultipleScopes: true
}
}
};
```
Add unit test in config entry.
> feat(cz-commitlint): support select scope with radio list by setting disableMultipleScopes

- README.md
- docs/guides-local-setup.md
> fix(docs): minor changes to guides

- @commitlint/is-ignored/src/defaults.ts
- @commitlint/is-ignored/src/is-ignored.test.ts
Updated wildcard regular expressions in `@commitlint/is-ignored`.
Merging a tag in another branch can lead to conflicts. In this case, the default Git commit message after resolving the conflicts will be like: `Merge tag 'x.y.z'`
There is specific plumbing to consider a branch merge commit as valid
```sh
echo "Merge branch 'a branch'" | commitlint 
```
But currently, a tag merge commit is being considered as an error:
```sh
echo "Merge tag 'a tag'" | commitlint 
⧗   input: Merge tag 'a tag'
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
```
So I updated the wildcards to get a consistent behavior between branch and tag merge:
- `Merge branch 'a branch'`
- `Merge tag 'a tag'`
Running commitlint with a tag merge commit: …
> fix(is-ignored): ignore merge tag commit messages

- @commitlint/cz-commitlint/src/SectionBody.test.ts
- @commitlint/cz-commitlint/src/SectionBody.ts
commit body should be empty by default
https://github.com/conventional-changelog/commitlint/issues/2971
> fix: commit body should be empty by default

- @commitlint/config-validator/src/__snapshots__/validate.test.ts.snap
- @commitlint/config-validator/src/commitlint.schema.json
- @commitlint/load/src/utils/load-parser-opts.test.ts
- @commitlint/load/src/utils/load-parser-opts.ts
Previously, `load` could accept `parserPresets` as both values and promises of
values. Per #2964 however, there was expectations for it to also support
functions returning said values.
This commit enables to specify `parserPresets` in all the same ways as
rules. That is, both commitlint rules and `parserPresets` can be specified as:
- Plain values
- Promises
- Functions returning plain values
- Functions returning promises
See discussion in #2964.
Wrote unit tests for `load-parser-opts` covering both new and old functionality.
> feat(load): accept functions as parser presets

- @commitlint/load/package.json
Add @types/node as a dependency of @commitlint/load to satisfy peer dependency from
cosmiconfig-typescript-loader (by way of ts-node's peer dependency of the same)
Fixes #3007
Depending on **@commitlint/prompt** or **@commitlint/cli** results in peer dependency warnings.
> Satisfy `cosmiconfig-typescript-loader` peer dependency

- .gitignore
- @commitlint/config-lerna-scopes/fixtures/nested-workspaces/@packages/a/nested-a/node_modules/dependency-a/package.json
- @commitlint/config-lerna-scopes/fixtures/nested-workspaces/@packages/a/nested-a/package.json
- @commitlint/config-lerna-scopes/fixtures/nested-workspaces/@packages/b/nested-b/node_modules/dependency-b/package.json
- @commitlint/config-lerna-scopes/fixtures/nested-workspaces/@packages/b/nested-b/package.json
- @commitlint/config-lerna-scopes/fixtures/nested-workspaces/package.json
- @commitlint/config-lerna-scopes/index.js
- @commitlint/config-lerna-scopes/index.test.js
For nested workspaces, the config rules also gave the name of the packages' dependencies as Lerna scope.
The issue of https://github.com/conventional-changelog/commitlint/issues/3023
> Ignoring node_modules folders inside nested workspaces as Lerna scopes

- docs/reference-configuration.md
Fix a typo in file `docs/reference-configuration.md`: 
```diff
- resolveable
+ resolvable
```
Found a typo error while reading and wanted to help fix it.
Since it is only a document modification, no testing is required
> docs: fix typo in 'reference-configuration.md'

- docs/guides-local-setup.md
Executing 
```
npx husky add .husky/commit-msg 'npx --no -- commitlint --edit $1'
yarn husky add .husky/commit-msg 'yarn commitlint --edit $1'
```
doesn't seem to produce desired .husky/commit-msg file content
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
npx --no -- commitlint --edit $1
```
instead it produces
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
npx --no -- commitlint --edit 
```
because $1 is interpolated, adding slash doesn't seem to help, hence suggested fix (fix is bit ugly I admit, up to you guys to accept it or fixing it your way)
```js
```
```sh
```
> docs: husky add .husky/commit-msg docs fix

- @commitlint/cli/src/cli.ts
- README.md
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace git.io within the error message with its original URL.
> docs: replace all `git.io` links with their actual urls

- @commitlint/rules/src/footer-leading-blank.test.ts
- @commitlint/rules/src/footer-leading-blank.ts
- README.md
`footer-leading-blank` had a bug: It calculated the start line of the body and added the number of body lines to identify the line before the footer. This will not work if the body contains a comment line, as it is not counted as "body line".
The new implementation looks for the first footer line and selects the line before.
This way the line above the footer will be identified correctly, assumed the first footer line is not existent as a previous line in the body.
Example of bug: `bodyLines.length` will be 2 in the following example, as the comment was filtered out
```
feat: feature
Body Line 1        <-- this line was identified as first body line
Body Line 2        <-- this is the line after the body as it is line 3 + 2 and therefore it should be empty
footer: value
```
See …
> fix(rules): footer-leading-blank should work with body comments

- README.md
Process of registering commit-msg hook doesn't seem to be reliable, let's maybe replace it with solution suggested in other PR https://github.com/conventional-changelog/commitlint/pull/3113
```js
```
```sh
```
> Since it doesn't work well anyway,let's replace it

- @commitlint/config-nx-scopes/index.js
- @commitlint/config-nx-scopes/readme.md
Adds the ability to filter the scopes provided by @commitlint/config-nx-scopes by Nx project type (e.g. only load projects of type 'application')
Users of Nx repos with lots of libraries may not want _every project_ available as an option for a commit's scope.
```js
const {
utils: { getProjects }
} = require('@commitlint/config-nx-scopes')
rules: {
'scope-enum': async ctx => [
2,
'always',
[...(await getProjects(ctx, 'application'))]  // ⬅ or 'library'
]
}
}
```
`npm link` and used locally
Solves: #3152
> feat: add ability to filter Nx projects in @commitlint/config-nx-scopes

- @commitlint/config-conventional/README.md
- docs/reference-rules.md
&emsp;Update the `scope-case` rule in [docs/reference-rules.md](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md) and [@commitlint/config-conventional/README.md](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/README.md) to be same.
&emsp;To fix #3159.
> docs: align subject case rule in readme #3159

- @commitlint/config-conventional/README.md
&emsp;Removed `scope-case` rule from [@commitlint/config-conventional/README.md](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/README.md) to update the documentation.
&emsp;I referenced to the #828 . The pr modified [@commitlint/config-conventional/index.js](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js). Verification of scope-case has been removed. But the documentation was not updated together.
&emsp;And to fix #3157 .
&emsp;Removed the following contents from the documentation. 
- **condition**: `scope` is in case `value`
- **rule**: `always`
- **level**: `error`
```
'lowerCase'
```
```sh
echo "fix(SCOPE): some message" # fails
echo "fix(scope): some message" # passes
```
> docs: remove scope-case rule #3157

- @commitlint/config-nx-scopes/fixtures/basic/nx.json
- @commitlint/config-nx-scopes/fixtures/basic/package.json
- @commitlint/config-nx-scopes/fixtures/empty/package.json
- @commitlint/config-nx-scopes/index.js
- @commitlint/config-nx-scopes/package.json
- yarn.lock
This PR moves support for Nx 14.
See https://github.com/conventional-changelog/commitlint/pull/3132
The Nx team has been working to consolidate their CLI related tools into the `nx` package.
Specifically we are looking at commit  [`6f038e`](https://github.com/nrwl/nx/commit/6f038e7a4a4fe27dd218138fd21b46541761aec9).
As of version [`13.9.0`](https://github.com/nrwl/nx/releases/tag/13.9.0) they have released a migration path for this within Nx.
Now that Nx [`14.0.0`](https://github.com/nrwl/nx/releases/tag/14.0.0) has been release we need to make sure we transition the `@commitlint/config-nx-scopes` as well.
This should largely be considered a **breaking change** even if some level of backward compatibility is possible depending on the user existing workspace configuration.
> Migrate @nrwl/tao to nx following 13.9.0 release

- @commitlint/cli/fixtures/comment-char/commitlint.config.js
- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @packages/test/src/git.ts
- package.json
- yarn.lock
When parsing `.git/COMMIT_EDITMSG` use the `core.commentChar` git setting if present, falling back to the default comment char `#` otherwise.
Use the `parserOpts.commentChar` setting only when parsing other messages (e.g. from stdin.)
See #3190.
```js
```
```sh
test=$(printf "fix: foo\n\n$" && printf -- '-%.0s' {1..200})
echo $test | commitlint # fails, line too long and not using edit mode
git config core.commentChar %
commitlint --edit /dev/fd3 3<<<$test # fails, line too long and different comment char
git config core.commentChar $
commitlint --edit /dev/fd3 3<<<$test # passes
```
With the usage example above.
> Use `core.commentChar` from git config with `--edit` flag

- @commitlint/config-validator/package.json
- @commitlint/config-validator/src/__snapshots__/validate.test.ts.snap
- @commitlint/config-validator/src/commitlint.schema.json
- @commitlint/config-validator/src/formatErrors.ts
- @commitlint/config-validator/src/validate.ts
- yarn.lock
ajv introduced some breaking changes from v6 to v7, and from v7 to v8. Most can
be found in [their migration guide](https://ajv.js.org/v6-to-v8-migration.html).
This commit addresses the following:
- `ErrorObject.dataPath` was renamed to `ErrorObject.instacePath`
- Wordings of some errors changed (e.g. "should" -> "must")
- Strict mode does not allow a top-level `default` value
- Strict tuple checking was confused by the `rule` array definition, see
[Unconstrained tuples](https://ajv.js.org/strict-mode.html#unconstrained-tuples)
- The `plugins` schema included an invalid object definition for `rules`
- `schemaId` is no longer an ajv option
- `missingRefs` no longer seems to affect the usage of ajv in the project
- `addKeyword` has its signature changed
The tests pass and everyone's …
> chore(config-validator): update ajv to v8

- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/cli/src/types.ts
- @commitlint/read/package.json
- @commitlint/read/src/get-history-commits.ts
- @commitlint/read/src/read.test.ts
- @commitlint/read/src/read.ts
- yarn.lock
> feat(commitlint): add additional git log args

- @commitlint/config-conventional/README.md
Update subject-case rule in [@commitlint/config-conventional/README.md](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/README.md).
To fix #3340
> docs: correct subject case rule in readme config-conventional #3340

- README.md
updated the "commit-msg" hook creation. Fixed `ENOENT: no such file or directory, open` error on pre-commit
Following the docs mentioned [here](https://commitlint.js.org/#/guides-local-setup) I noticed 2 things.
1. The file creation portion doesn't work for me (using macOS Or WSL Ubuntu on Windows)
2. When I create the file manually - the commit-msg hooks gives the error `ENOENT: no such file or directory, open` error on pre-commit`
1. updated the file creation to use echo and the output redirection operator.
2. noticed the error `ENOENT: no such file or directory, open` error on pre-commit` is to do with the sting interpellation.
changed the string from `"\${1}"` to `\${1}` (removed the quotes)
In the root of the project directory, can now just run
```bash
echo '
#!/bin/sh
. "\$(dirname …
```
> docs(README.md): update husky hook file creation

- docs/README.md
Usage was non-native. Should be either "help your team in adhering", "help your team to adhere", or "help your team adhere." Chose the last option because it's shorter. Sorry I have no citation for this.
> docs: English syntax correction

- @commitlint/cli/fixtures/warning/commitlint.config.js
- @commitlint/cli/src/cli-error.ts
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/cli/src/types.ts
Added a flag which changes the result codes:
result codes (`-s, --strict`):
- 0 success
- 1 runtime error (e.g. invalid config)
- 2 linter warning
- 3 linter error
result codes (default):
- 0 success / linter warning
- 1 runtime error / linter error
issue: #3384
```js
rules: {
'type-enum': [2, 'always', ['feat']],
'subject-max-length': [1, 'always', 4]
}
};
```
```sh
echo "feat: 12" | commitlint -s # exit 0
echo "feat: 12" | commitlint -s a # exit 1
echo "feat: 123456" | commitlint -s # exit 2
echo "feat2: 123456" | commitlint -s # exit 3
```
- Added new tests to the coverage
- all usage examples
> feat(cli): add strict mode (#3384)

- @commitlint/config-nx-scopes/package.json
Update NX dev and peer dependencies version to version ^15.0.0
Fixes #3413.
A new NX version was release some days ago and when you update NX in our repository, npm install fails with `Conflicting peer dependency: nx@14.8.6` as @commitlint/config-nx-scopes has a peerDependency set to ^14.0.0 for NX.
The way @commitlint/config-nx-scopes search for the scopes (NX projects) is not affected, so this is only an update in package.json. 
I also updated the fixture files to have the latest version format, but this does not affect this plugin.
I have changed the NX version in peerDependency to ^15.0.0 (instead of support both 14 and 15). Not sure if it is better to add it as `^14.0.0 || ^15.0.0`, if so, please let me know, and I will change it
```js
``` …
> feat(config-nx-scopes): update nx dependency version to ^15.0.0

- @commitlint/config-lerna-scopes/package.json
See https://github.com/conventional-changelog/commitlint/issues/3409.
Even with the peerDependencies: optional, npm will *still* kick and scream and end your process if you try to use this with lerna v6.
Note that this is NOT a breaking change - and simply allows people with lerna v6 to work with the package. People on lerna v5 will not even notice the difference.
Allows this package to work with lerna v6
See above
```js
```
```sh
```
> build: Expand lerna version range to accept v6

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/config-patternplate/index.js
- @commitlint/config-patternplate/package.json
- @commitlint/cz-commitlint/package.json
- @commitlint/cz-commitlint/src/Process.test.ts
- @commitlint/cz-commitlint/src/store/prompts.ts
- @commitlint/ensure/package.json
- @commitlint/ensure/src/index.test.ts
- @commitlint/ensure/src/to-case.ts
- @commitlint/load/package.json
- @commitlint/load/src/load.ts
- @commitlint/prompt/package.json
- @commitlint/resolve-extends/package.json
- @commitlint/resolve-extends/src/index.ts
- package.json
- yarn.lock
> chore: remove lodash

- @commitlint/config-conventional/index.test.js
Removed superfluous trailing arg from function call, as the function only accepts one param:
https://github.com/conventional-changelog/commitlint/blob/c86597c926e3b50ae86d500554f74798bcf4f6c9/%40commitlint/config-conventional/index.test.js#L4
Code tidiness.
N/A
N/A
> test(config-conventional): remove superfluous trailing arg

- @commitlint/config-lerna-scopes/index.js
- @commitlint/config-lerna-scopes/package.json
- @commitlint/config-patternplate/index.js
- @commitlint/config-patternplate/package.json
- @commitlint/ensure/package.json
- @commitlint/ensure/src/index.test.ts
- @commitlint/rules/package.json
- @commitlint/rules/src/index.test.ts
- yarn.lock
- added `glob` as a dependency in the packages that used `globby`
- removed `globby` as a dependency
- replaced (mostly async) functions from `globby` with (sync) function from `glob`
- did one modification because `globby` accepted an array of string as param, but `glob` accepts only one string as param
Closes #2370 
I ran all of the tests with the `yarn test` command. I'm not sure does this change needs new tests, but if so, I'm happy to add them.
> chore: change globby library to glob

- @commitlint/load/src/utils/load-config.ts
- README.md
Adding support for `.cts` format. As per this issue: https://github.com/conventional-changelog/commitlint/issues/902. Where support for `.cjs` was added.
Tests passing. And i tested cosmiconfig in a local playground to make sure all is done correctly
(The PR that added cjs didn't add tests. And doesn't seem neccessary (simple). I did test manually on a real project. By directly injecting the changes. And it works.)
> feat: support config .cts  extension

- docs/reference-community-projects.md
I created a plugin for commitlint
```js
```
```sh
```
> docs: add commitlint-plugin-selective-scope

- docs/reference-rules.md
This is just a doc formatting update. I added syntax highlighting to code examples, and aligned the comments in the arrays to make them easier to read
The change is from this:
```js
'sentence-case', // Sentence case
'snake-case', // snake_case
'start-case' // Start Case
```
to this:
```js
'sentence-case', // Sentence case
'snake-case',    // snake_case
'start-case'     // Start Case
```
This makes it easier to parse the list of rules and definitions at a glance.
> chore: add syntax highlighting and format arrays in doc

- @commitlint/load/package.json
Moved the `@types/node` from `dependencies` to `devDependencies`
I am using a mono repo and all my packages use a single version of `@types/node`. Since, the `@types/node` in this `@commitlint/load` package is very old and doesn't match the version in my projects, it creates a different node_modules directory for all my sub-projects because of this version mis-match.
Build succeeds
> chore: move @types/node to devDependencies

- @commitlint/parse/src/index.test.ts
- @commitlint/parse/src/index.ts
Fixes https://github.com/conventional-changelog/commitlint/issues/3428
In the current version of commitlint the body is truncated unexpectedly when there is a pattern like '- Something between dashes -' in the commit message body. I investigated this issue https://github.com/conventional-changelog/commitlint/issues/3428 and noticed that the reason for this behavior is that in the commit parser package the commitlint uses ([conventional-commit-parser](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/README.md)), this pattern '- something -' is a special pattern for any arbitrary filed. For example, if you put '-myNote-' in the commit message body, everything that comes after this field will be saved in an arbitrary field …
> fix: stop truncating the body in presence of dashes

- @commitlint/load/package.json
Update to this: https://github.com/conventional-changelog/commitlint/pull/3464
> chore: convert @types/node version to *

- @commitlint/load/src/utils/load-config.ts
This PR fixes a bug which was introduced in commitlint v17.4.0 (https://github.com/conventional-changelog/commitlint/commit/85ad18b8990567df516effcacbf04edbcbb6b6d7). If two instances of TypeScriptLoader() are used a .ts commitlint config is somehow compiled twice. This leads sometimes, depending on the config, to a compilation error.  
A repository which contains the code to reproduce the error, can be found [here](https://github.com/mailaenderli/commitlinit-bug-repro).  
Fixes a minor bug
```
"not a conventional commit" | npx commitlint
```
`.commitlintrc.ts`
```
const dummyGetScope = (ctx: any) => 'testScope'
const config = {
extends: ['@commitlint/config-conventional'],
rules: {
'scope-enum': async (ctx: any) => [2, 'always', [...(await dummyGetScope(ctx)), 'your', 'other', 'scopes']] …
```
> Fixes a bug when a ts commitlint config is compiled twice

- docs/reference-configuration.md
There is the following enum for checking rule config severity in `commitlint/@commitlint/types/src/rules` that we should use in typescript plugins instead of 0, 1, and 2 numbers to make the code clearer.
```
export enum RuleConfigSeverity {
Disabled = 0,
Warning = 1,
Error = 2,
}
```
To make the docs clearer.
It has been used in our local plugins.
> docs: use RuleConfigSeverity in config docs

- @commitlint/parse/src/index.test.ts
- @commitlint/parse/src/index.ts
- @commitlint/types/src/parse.ts
This allows the [`fieldPattern` option for `conventional-commits-parser`](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/README.md#fieldpattern) to be set via `parserOpts` in user config.
This is related to the discussion at https://github.com/conventional-changelog/commitlint/pull/3476#issuecomment-1420160206. That PR accidentally prevented any user from being able to set a custom `fieldPattern` option.
I've also added `fieldPattern` to the `ParserOptions` type definitions. Either it was missed when the types were first created, or the option was later added to `conventional-commits-parser` (I'm not sure which).
1. Unit tests.
2. Manual testing in a separate project. It had previously relied on the implicit default …
> fix(parse): allow setting fieldPattern in parserOpts

- docs/guides-ci-setup.md
Fixes the documentation to advise using fetch-depth: 0, which is needed for `commitlint --from` to check against the history of commits.
> fix(docs): checkout requires fetch-depth: 0

- @commitlint/config-pnpm-scopes/index.js
- @commitlint/config-pnpm-scopes/package.json
- yarn.lock
Refactor to remove peer dependencies from config-pnpm-scopes
Closes https://github.com/conventional-changelog/commitlint/issues/3556
```
yarn test
```
> fix(config-pnpm-scopes): refactor to remove peer dependencies

- @commitlint/load/package.json
- package.json
- tsconfig.shared.json
- yarn.lock
Have `@commitlint/load` support both `^4.6.4` and `^5.0.0` as supported versions and update the base typescript version used in the repo to the current latest version `^5.0.2`.
Also removed the now deprecated `keyofStringsOnly` setting from `tsconfig.shared.json`.
Fixes #3562
Allows `commitlint` to be used in a `typescript@^5` repository.
Ran the tests
> Support typescript 5.0

- @commitlint/read/package.json
Upgrade git-raw-commits to 2.0.11 due Vulnerability  https://github.com/advisories/GHSA-7p7h-4mm5-852v
> Upgrade package to overcome Vulnerability

- @commitlint/rules/src/subject-case.test.ts
- @commitlint/rules/src/subject-case.ts
Implements #3574 by modifying the `subject-case` rule first character pre-check so that it allows any Unicode letter instead of just Latin alphabet letters.
This enables usage of `subject-case` rule with any language input instead of just English.
Previously, the rule required first symbol of a subject message to be Latin alphabet's letter.
That requirement was introduced with PR #451 and basically made anyone writing commit messages in non-English blocked out of using this rule, and without a note about that quirk in the docs.
```js
extends: ["@commitlint/config-conventional"],
rules: {
"subject-case": [2, "never", "lower-case"]
}
};
```
```sh
echo "test: ûnderwerp" | commitlint
```
I've added some tests for different languages and cases. The …
> feat(rules): expand Latin-only characters limitation for `subject-case` rule with Unicode support

- @commitlint/rules/src/subject-case.test.ts
- @commitlint/rules/src/subject-case.ts
A quick fix for #3585 
Excludes Other Letter category from Unicode regex (which matches case-less symbols, so such strings can't be validated at all) introduced in PR #3574.
```js
extends: ["@commitlint/config-conventional"],
rules: {
"subject-case": [2, "never", "sentence-case"]
}
};
```
```sh
echo "refactor(test): 这是一次提交" | commitlint # passes
```
Added some more tests to make sure this case is covered as well.
> fix(rules): avoid processing strings with case-less Letter category symbols in `subject-case`

- @commitlint/parse/src/index.ts
This PR adds a named export alongside a default export, which fixes imports in an ESM context.
- When working on https://github.com/TanStack/query/pull/5486, I came the following issue trying to run `scripts/publish.mjs`: `TypeError: parseCommit is not a function`
- The script uses `import parseCommit from '@commitlint/parse'` then later calls `const parsed = await parseCommit(d.subject)`, and no typechecking errors are raised (using `@ts-check`)
- However, if I instead call `const parsed = await parseCommit.default(d.subject)` I get a type error, but the script works without issues (see [here](https://github.com/TanStack/query/commit/d1b001a46f7959441283b59709a4e0b59a019dae))
- This seems to be some weird ESM/CJS incompatibility ([this](https://github.com/evanw/esbuild/issues/1719) might …
> Add named export to @commitlint/parse

- docs/guides-local-setup.md
Just a quick fix of grammar spotted in docs.
```js
```
```sh
```
> docs: fix grammar in sentence

- README.md
- docs/guides-local-setup.md
The instructions regarding local setup wee a bit confusing, particularly in the "Add hook" section where npx was used to run `commitlint` instead of the locally installed package.
I have updated the instructions to provide greater clarity and accommodate those who prefer a 100% local setup. The revised steps now include guidance on utilizing the locally installed `commitlint` package.
When I read the documentation to use `commitlint` I was confused by the local setup using `npx` to run the command instead of the package installed locally 
```sh
npm pkg set scripts.commitlint="commitlint --edit"
npx husky add .husky/commit-msg 'npm run commitlint ${1}'
```
Follow the instructions on the doc, section `Add hooks`:
```sh
npm pkg set scripts.commitlint="commitlint --edit"
npx husky add …
```
> docs: add instructions to use the package installed locally

- @commitlint/load/package.json
- yarn.lock
Hi everyone, I haven't contributed to a public repo before and don't have push access, so not sure I've done this right, but I've forked off the original repo and push a branch.
Upgrades the cosmiconfig-typescript-loader dependency in @commitlint/load to move away from a production dependency on ts-node.
Prior to cosmiconfig-typescript-loader@5, ts-node was used to transpile Typescript files, which required it and typescript to be declared as production dependencies in @commitlint/load. In v5, cosmiconfig switched to using https://www.npmjs.com/package/jiti in place of ts-node (https://github.com/Codex-/cosmiconfig-typescript-loader/releases/tag/5.0.0).
As a result, I have removed the dependency on ts-node, and cleaned up the dependencies for @commitlint/load - removed unused dependencies …
> feat(load): Remove dependency on ts-node for @commitlint/load

- docs/reference-rules.md
resolves #3638
1. `subject-case` uses the standard `condition` language
2. `subject-case` "possible values" to use `// lower case` instead of `// default`
- #3638
N/A
- It hasn't. See #3639
- I didn't run the tests, after hitting #3639. Does not change anything that would affect tests.
> docs: clarify subject-case [resolves #3638]

- docs/reference-rules.md
A small change to update default value of type-enum based on [config-conventional document](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional)
```js
```
```sh
```
> docs: update type-enum default value

- .github/workflows/container-build.yml
Build and push only releases and master branch (via cron).
Right now every branch that is created in the repo triggers build in the repository. This includes branches created by Renovate. We don't want it - only master (via cron) and releases should be built 
N/A
N/A
> fix: remove build on any branches except main and tags

- @commitlint/load/src/utils/load-config.ts
Lazy load `cosmiconfig-typescript-loader`
To avoid loading `cosmiconfig-typescript-loader` (and consequently ts-node/jiti) when not required (i.e. when the user has no typescript-based config file). Refer https://github.com/conventional-changelog/commitlint/issues/3256#issuecomment-1762790855. This unblocks the users facing #3256 and improves perf.
Manually tested on my project with the patch. The CI already has tests for TS-based config.
> feat: lazy load cosmiconfig-typescript-loader

- @commitlint/load/package.json
- yarn.lock
Link to original PR: https://github.com/conventional-changelog/commitlint/pull/3633
Just re-applying the changes.
> feat(load): use cosmiconfig-typescript-loader v5 to remove ts-node dependency

- .github/workflows/CI.yml
Use a test matrix in the CI file.
Switch to using a test matrix instead of separate build jobs. Also switch to using the setup-node action, which allows for pulling specific major/minor/patch versions of node.
Simplifies the CI configuration and allows for specific versions of node to run the pipeline.
N/A
If the CI checks all pass (and there are 4 of them - node 18/20 + ubuntu/windows).
N/A
- [ x ] All new and existing tests passed.
> chore: switch ci to test matrix

- @commitlint/load/package.json
`@commitlint/load` has both a regular and dev dependency on `@types/node`. Only one of these should be needed, and it seems that the regular dependency is not required since the package's API does not rely on these types, so I have removed it. The dev dependency needs to stay as `node:path` is used in this package.
The `@types/node` dependency could result in multiple major versions of `@types/node` in a consumer's `node_modules`, e.g. if a consumer also depends on `@types/node@20`. This isn't a huge deal, but IMO it's still worth fixing if possible.
N/A
The build output (specifically `.d.ts` files) before and after this change is identical.
> fix(@commitlint/load): Remove unused `@types/node` dependency

- @packages/utils/package.json
- @packages/utils/pkg-check.js
Removes the usage of `fs-extra` from the `@commitlint/utils` package. The package is not needed and adds a extra dependency
Remove unnecessary dependencies from the commitlint packages
> fix(utils): remove fs-extra usage

- @commitlint/read/package.json
- @commitlint/read/src/get-edit-commit.ts
- @commitlint/read/src/get-edit-file-path.ts
- @commitlint/read/src/read.test.ts
removes fs-extra usage and the dependency on `fs-extra` and uses the node.js `fs/promises` module
- removes usage of the `fs-extra` module from `@commitlint/read`
- removes dependency `fs-extra` and devDependency `@types/fs-extra` from the `@commitlint/read` package
remove a unnecessary dependency
> fix(read): remove fs-extra usage and use fs/promises

- README.md
Explicitly mention that the hook file name must be commit-msg for husky
Added a warning block in docs to make it clear that the name for husky hook file must be **commit-msg**.
A lot of people using this library with husky don't know about git hooks in general. So it's assumed that changing the name for hook file won't cause any problems. This change in documentation makes it clear that the name is actually really important.
[Issue 3780](https://github.com/conventional-changelog/commitlint/issues/3780)
No usage
No test required
> Update README.md to improve husky setup

- README.md
Explain how to run `commitlint` from the source code.
I could not find a way to test new rule from a command line using cloned source code. This should be it. `yarn install` doesn't make `commitlint` available. 
Is there a better way?
Manually `yarn run commitlint`.
> docs: how to run CLI for development

- .github/workflows/CI.yml
When a contributor wants to create a PR for commitlint, the normal thing for him to do first is fork the repo and create a branch with a different name than master. Then, if he pushes his commits, he should be able to see the CI status of his fixes before he opens the PR.
> GitHubCI: no need to just run in master branch

- @commitlint/config-nx-scopes/index.js
Updates logic to get nx projects list to use nx helper that works with newer nx versions
Fixes #3820
Using with nx 17.2.0 and higher fails with `Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.`
```js
module.exports = {extends: ['@commitlint/config-nx-scopes']};
```
```sh
```
Existing tests pass for each nx version
> fix(config-nx-scopes): restore compatibility with nx 17.2.0 and higher

- @commitlint/config-nx-scopes/index.js
- @commitlint/config-validator/src/validate.test.ts
- @commitlint/cz-commitlint/src/Process.test.ts
- @commitlint/cz-commitlint/src/store/rules.test.ts
- @commitlint/cz-commitlint/src/utils/rules.test.ts
- @commitlint/lint/src/lint.test.ts
- @commitlint/load/src/load.test.ts
- @commitlint/prompt/src/library/utils.test.ts
- @commitlint/resolve-extends/src/index.test.ts
Same energy as b3007ee37e26722a5f468ed24ca0012628149ea0.
> refactor: use enum instead of hardcoding

- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/cli/src/types.ts
- docs/reference-cli.md
fixes #3819
Now `print-config` cli option accept 3 possible parameters:
- `''` (empty) - same behaviour of current implementation
- `text` - same behaviour of current implementation
- `json` - prints a raw json
Parse the configuration from stdout
```sh
npx commitlint --print-config
npx commitlint --print-config=text
npx commitlint --print-config=json
```
Unit tests have been added to `@commitlint/cli/src/cli.test.ts` to test all 3 scenarios. 
`--help` test has been updated to match the new behaviour of `print-config`
> feat(cli): print-config now can be configured to print a json in stdout

- @commitlint/config-conventional/index.js
- @commitlint/rules/src/header-trim.test.ts
- @commitlint/rules/src/header-trim.ts
- @commitlint/rules/src/index.ts
- @commitlint/types/src/rules.ts
- docs/reference-rules.md
Followup  of https://github.com/conventional-changelog/commitlint/issues/3199#issuecomment-1531415980:
> Currently when having a leading space, the error message says that the subject is empty.
> I suggest that the error message instead says that there is leading whitespace.
> This is due to identifying extra unwanted leading whitespace is hard in a commit message.
I have added a rule to check that header do not start or end with whitespace characters: `header-trim`
The rule logs a different status message for each scenario (start / end / mixed).
I added the new rule to `@commitlint/config-conventional` config. 
Let me know if you prefer that the user manually opt-it or it I have to add it to other configurations.
#3199
```js
rules: { …
```
> feat(rules): add header-trim rule

- .github/CONTRIBUTING.md
- .husky/commit-msg
- .husky/pre-commit
- README.md
- docs/guides-local-setup.md
- package.json
- yarn.lock
`husky` has been updated to `v9`.
Closes #3873
[husky migration guide instructions](https://github.com/typicode/husky/releases/tag/v9.0.1)
- `package.json` script `postinstall` has been removed and replaced by `"prepare": "husky"` as per new setup instructions
- husky hooks have been recreated using the new procedure `echo "{...}" > .husky/{...}`
- Release procedure information has been moved to `.github/CONTRIBUTING.md` 
- "Getting started" is very similar to the one in the website so I think that is better to simply create a link to the website.
By doing so setup maintenance effort should be reduced.
Local setup instructions have been updated.
For shell instructions I created an accordion item for each single package manager. 
I added just `npm` and `yarn` but let me know if I need to …
>  docs: update husky to v9

- .github/workflows/CI.yml
This way we will make sure that any dependency upgrades don't make commitlint lose compatibility with the default version shipped with an LTS version of Ubuntu, starting with 24.04.
This is, IMO, important, because AFAIU commitlint lost, some months ago, compatibility with the NodeJS version shipped with Ubuntu 22.04, and thus it requires its users to install NodeJS from external sources, which is a potential security risk (and stability risk because of needing to rely on more bleeding edge versions).
> CI: add an Ubuntu LTS job

- .github/workflows/CI.yml
Add a new `codeQuality` job inside `CI` workflow.
The new job runs before `build` and `nodeJsBaselineAptCompatibility`.
Executed task are:
1. `yarn build`
2. `yarn format`
3. `yarn lint`
This should avoid lints error addition if someone forgets to run `yarn lint`.
During #3850 I noticed that a lint issue fix was performed with a separate [commit](https://github.com/conventional-changelog/commitlint/pull/3850/commits/6aaa6c1526735489e7dcf80518da6fd6526b1376).
Basically `config-nx-scopes` was missing `@commitlint/types` dependency and running `yarn lint` shows that error.
You can see the same fix also on the [fix lodash PR](https://github.com/conventional-changelog/commitlint/pull/3901/commits/e72eba4433ead94efd9c628d4330b81e1a0cbe82)
N/A
N/A
> ci: add codeQuality job to run lint and format task

- @alias/commitlint/cli.test.js
- @alias/commitlint/package.json
- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/config-pnpm-scopes/package.json
- @commitlint/load/package.json
- @commitlint/prompt-cli/cli.js
- @commitlint/prompt-cli/cli.test.js
- @commitlint/prompt-cli/package.json
- @commitlint/prompt/package.json
- @commitlint/read/package.json
- @commitlint/read/src/read.test.ts
- @commitlint/resolve-extends/package.json
- @commitlint/rules/package.json
- @commitlint/rules/src/trailer-exists.ts
- @commitlint/top-level/package.json
- @commitlint/top-level/src/index.ts
- @commitlint/travis-cli/package.json
- @commitlint/travis-cli/src/cli.test.ts
- @commitlint/travis-cli/src/cli.ts
- @packages/test/package.json
- @packages/test/src/fix.ts
- @packages/test/src/git.ts
- @packages/utils/dep-check.js
- @packages/utils/package.json
- @packages/utils/pkg-check.js
- package.json
- yarn.lock
`yarn outdated` output after this PR:
```log
Package     Current  Wanted   Latest   Workspace                       Package Type    URL                                                                      
@types/node 18.19.17 18.19.17 20.11.19 @commitlint/cli                 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
@types/node 18.19.17 18.19.17 20.11.19 @commitlint/load                devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
cosmiconfig 8.3.6    8.3.6    9.0.0    @commitlint/load                dependencies    https://github.com/cosmiconfig/cosmiconfig#readme                        
glob        8.1.0    8.1.0    10.3.10  @commitlint/config-lerna-scopes dependencies …
```
> chore: bump ESM only packages and minor version packages

- @commitlint/config-lerna-scopes/index.js
- @commitlint/config-lerna-scopes/package.json
- @commitlint/config-patternplate/package.json
- @commitlint/ensure/package.json
- @commitlint/ensure/src/index.test.ts
- @commitlint/is-ignored/package.json
- @commitlint/load/fixtures/recursive-parser-preset-conventional-atom/first-extended/second-extended/package.json
- @commitlint/rules/package.json
- @commitlint/rules/src/index.test.ts
- @packages/test-environment/package.json
- @packages/test/package.json
- @packages/utils/package.json
- yarn.lock
After trying, `glob` can be upgraded safely and easily while `cosmiconfig` cannot, so I'll hold on upgrading `cosmiconfig`.
~~I'll start to add some changesets in this PR at the same time.~~
I found we're actually managing changelog with lerna + commit message, so there seems nothing left blocking releasing now.
For the following
> change to use exports field in [package.json](https://nodejs.org/api/packages.html#exports) (via @marcalexiei)
I'm not for sure to confirm whether it is a must-to-have action because we're using pure ESM now, `exports` is not required in this case.
> chore: bump `glob` and related usage

- @commitlint/cli/package.json
- @commitlint/cli/src/cli.ts
- @commitlint/load/src/load.test.ts
- @commitlint/load/src/load.ts
- @commitlint/resolve-extends/package.json
- @commitlint/resolve-extends/src/index.ts
- yarn.lock
> fix: drop `resolve-from`, `resolve-global` and `import-fresh`, resolve global packages correctly

- @commitlint/resolve-extends/package.json
- @commitlint/resolve-extends/src/index.ts
close #3936
This is only a workaround for Yarn P'n'P + pure ESM, but it's also good enough.
We'll still watch https://github.com/wooorm/import-meta-resolve/issues/23
```js
```
```sh
```
> fix: fallback to `resolve-from` for Yarn P'n'P

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
* Moved 'Steps to reproduce' section before Current/Expected behaviour.
* Moved 'Current behaviour' before 'Expected behaviour'.
This way it feels more natural.
> chore: reorder 2 BUG_REPORT.yml elements

- @commitlint/lint/src/lint.test.ts
- @commitlint/lint/src/lint.ts
- docs/.vitepress/config.ts
- docs/support/troubleshooting.md
Closes #3894.
I added a new section in the documentation with the step to troubleshoot error similar to the one described on #3894.
I also made two additional changes:
- I changed the error message to be more simple IMHO.
- I used `RuleConfigSeverity` enum to compute outcome `warnings` and `errors`. 
(The enum was already imported)
#3894
N/A
`yarn test`
> add troubleshoot on documentation  and some lint minor refactors

- @commitlint/config-angular-type-enum/package.json
- @commitlint/config-nx-scopes/package.json
- @commitlint/config-patternplate/package.json
- @commitlint/config-pnpm-scopes/package.json
- @commitlint/config-rush-scopes/package.json
- @commitlint/prompt-cli/package.json
- @commitlint/travis-cli/package.json
Fixes #3948
Fixes #3952
Some packages `package.json` do not have the `main` key to define their default export.
I added  the `main` key and when necessary the `types` key.
N/A
yarn test
> fix: add `main` and `types` keys in package.json

- @commitlint/cz-commitlint/README.md
The inquirer version of peerDependencies has been updated in https://github.com/conventional-changelog/commitlint/commit/342373559bdf7c783c4ef37ff05dc38a5f681159
The command before the change will cause an error in the latest version.
```
npm install --save-dev @commitlint/cz-commitlint commitizen inquirer@8
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: inquirer@8.2.6
npm ERR! node_modules/inquirer
npm ERR!   dev inquirer@"8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer inquirer@"^9.0.0" from @commitlint/cz-commitlint@19.0.3
npm ERR! node_modules/@commitlint/cz-commitlint
npm ERR!   dev @commitlint/cz-commitlint@"*" from the root project
npm ERR! …
```
> docs: Update cz-commitlint install command

- @commitlint/resolve-extends/src/index.ts
related https://github.com/wooorm/import-meta-resolve/issues/24
It fixes a possible issue when using a dual-package config, without this change, commonjs entry could be resolved, with this change, ESM entry will be preferred correctly.
```js
```
```sh
```
> fix: add missing `conditions` param for `moduleResolve`

- .eslintrc.cjs
- @commitlint/cz-commitlint/package.json
- @commitlint/cz-commitlint/src/index.cjs
- @commitlint/cz-commitlint/src/index.cts
resolves #3949
Currently `comittizen` does not support ESM adapter, this PR add additional CJS export for `@commitlint/cz-commitlint`, which allows `comittizen` to work with it.
https://github.com/conventional-changelog/commitlint/pull/3850#issuecomment-1984932236
This PR does not change usage.
`package.json`
```json
{
"config": {
"commitizen": {
"path": "@commitlint/cz-commitlint"
}
},
}
```
Install new `@commitlint/cz-commitlint` and run `commitizen`:
```
pnpm add -D https://pkg.csb.dev/conventional-changelog/commitlint/commit/a6401ba0/@commitlint/cz-commitlint
pnpm exec cz # works
```
> feat: add CJS export for cz-commitlint

- @commitlint/cz-commitlint/index.cjs
- @commitlint/cz-commitlint/package.json
- @commitlint/cz-commitlint/src/index.cjs
Follow up #3963, fixes the missing cjs entry for `@commitlint/cz-commitlint`
https://github.com/conventional-changelog/commitlint/pull/3963#issuecomment-1987544876
> fix: add missing cjs entry in package

- @commitlint/config-conventional/package.json
- package.json
> fix: add missing entry `wrapper.mjs`

- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/cli/src/types.ts
- @commitlint/read/package.json
- @commitlint/read/src/read.ts
- docs/guides/ci-setup.md
- tsconfig.shared.json
HEAD~1 is brittle because it would fail in single-commit scenarios.
Closes https://github.com/conventional-changelog/commitlint/pull/3892
> feat(cli): introduce new --last flag, to stop recommending HEAD~1

- @commitlint/load/package.json
- @commitlint/load/src/load.test.ts
- @commitlint/load/src/utils/load-config.ts
- README.md
- docs/reference/configuration.md
- yarn.lock
See relevant cosmiconfig [release notes](https://github.com/cosmiconfig/cosmiconfig/releases/tag/v9.0.0), and https://github.com/cosmiconfig/cosmiconfig/issues/334 for context.
Enable support for reading `commitlint` configuration directly from [`package.yaml`](https://github.com/pnpm/pnpm/pull/1799).
```yaml
commitlint:
extends:
- "@commitlint/config-conventional"
rules:
body-case: [2, always, sentence-case]
```
> feat(load): update cosmiconfig to v9 to add support for `package.yaml` config

- @commitlint/config-nx-scopes/index.js
As the package is now pure ESM, we need to add the file extension to imports from nx as they are not coming from a package.json export field (https://nodejs.org/api/esm.html#esm_mandatory_file_extension).
By adding the file extensions, the modules get resolved again.
Fixes https://github.com/conventional-changelog/commitlint/issues/3978
Verified on https://github.com/timonmasberg/commitlint-nx-bug, which is a reporduction for the bug.
> fix(config-nx-scopes): include file extension in nx imports

- @commitlint/cli/fixtures/last-flag-regression/commitlint.config.js
- @commitlint/cli/src/cli.test.ts
- @commitlint/read/src/read.ts
Fix regression when running commitlint with `--last` flag. Add regression test for it.
Fixes https://github.com/conventional-changelog/commitlint/issues/3981
> Fix regression when using --last flag

- docs/guides/ci-setup.md
The syntax of the circleci config.yml was out of date.
```js
```
```sh
```
> Update circleci ci-setup.md

- @commitlint/is-ignored/src/defaults.ts
- @commitlint/is-ignored/src/is-ignored.test.ts
This PR allows a commit whose subject is prefixed with "amend!" to be ignored. 
`git-commit` supports the `--fixup=[(amend|reword):]<commit>` option, which creates a commit whose subject is prefixed with "amend!". commitlint should ignore this, but currently, it does not.
For more information about the `--fixup=[(amend|reword):]<commit>` option, please see the [git-commit documentation](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---fixupamendrewordltcommitgt).
n/a
According to the contribution guide.
> fix(is-ignored): ignore "amend!" commits

- @commitlint/config-nx-scopes/readme.md
`require()` imports no longer supported. Removed use of `require()` and replace with `import()`.
Fixes #4036 
(in updated docs)
n/a
> docs: Update nx project filtering documentation

- Dockerfile.ci
- docs/guides/ci-setup.md
This PR adds @commitlint/config-nx-scopes package to the container
Nx is a very popular tool for monorepos and this change allow the validation of nx scopes using the docker image
> feat(container): added @commitlint/config-nx-scopes for nx monorepos

- docs/guides/getting-started.md
- docs/guides/local-setup.md
Added `pnpm` to the `getting started` and `local setup` guides in the documentation
I hope these changes will help other developers that use pnpm easily set up commitlint
> docs: :memo: add pnpm to the getting started and local setup guides

- .github/workflows/container-build.yml
- Dockerfile.ci
> feat(container): add arm64 build

- @commitlint/prompt/src/input.test.ts
- @commitlint/prompt/src/inquirer/InputCustomPrompt.ts
- @commitlint/prompt/src/inquirer/inquirer.d.ts
- @commitlint/prompt/src/library/get-prompt.ts
My attempt to fix the prompt not respecting `body-leading-blank` setting issue in #3826 .
> fix(prompt): prompt does not respect [body-leading-blank] setting

- .github/workflows/CI.yml
Now that 24.04 has been released, 'apt upgrade' is not needed anymore for this job.
> ci: rm unneeded apt upgrade

- .github/workflows/CI.yml
- package.json
The schedule trigger will run CI everyday to make
sure we catch any breakage caused by external
reasons. The workflow_dispatch one is so that the
repo owner can launch CI jobs manually.
> ci: add schedule&workflow_dispatch triggers

- docs/reference/rules.md
* fixing typo of example from subject-case rule
* 
From '.' to ','
other example ended with ','
Not related
Just documentation
> docs: fixing rules.md

- docs/guides/ci-setup.md
See https://github.com/conventional-changelog/commitlint/issues/4103
I removed `stages` key, because copy/pasting the block may break stages that people have defined already.
```js
```
```sh
```
> docs: remove GitLab clone depth limitation

- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- docs/reference/cli.md
This PR enables yargs' first-class support for a [command line options file](https://yargs.js.org/docs/#api-reference-configkey-description-parsefn). It works out of the box and costs very little.
Also updated the CLI options docs while I was here.
The commitlint CLI has many arguments now; I counted 20. Composing and encoding all the required arguments for a project at the terminal or in a package script can get hard to maintain. The ability to move those options to a regular JavaScript or JSON module makes them far easier to manage. It is more human readable and writable.
This fabricated example is deliberately verbose and a bit unrealistic to make the point:
```diff
{
-   "commit:lint": "commitlint --from $GIT_LAST_TAG --format @some/formatter --parser-preset @some/preset --extends …
```
> Support command line options from a file

- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/cli/src/types.ts
- @commitlint/read/src/read.test.ts
- @commitlint/read/src/read.ts
- docs/reference/cli.md
Resolves #2507, which has the full problem statement. Also fixed a bug with the `--last` option.
~In draft mode to get the discussion going. Will open it up for real after more thorough testing.~ Testing complete (see below) and this is now ready to review.
See #2507.
Note that if there are no tags, such as in a brand new repo, commitlint will always pass. The idea is that it should be possible to add `commitlint --from-last-tag` to CI at the very beginning of a repo and never remove it. There is no need to document special steps, like adding an initial tag.
```sh
commitlint --from-last-tag
```
Unit tests and locally against this repo:
```sh
yarn run commitlint --from-last-tag --verbose
```
<details><summary>Output</summary>
</details>
> Support linting from the last tag

- @commitlint/load/src/utils/plugin-naming.ts
1. Removed unnecessary case insensitivity flag
2. Removed unnecessary capturing group
3. Replaced String.match with RegExp.exec https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-regexp-exec.html#regexp-prefer-regexp-exec
It slightly improves performance and removes redundancy
It's a pretty local change, I just looked at it
> Improve regex in @commitlint/load

- docs/index.md
- docs/reference/configuration.md
Prior to this commit, there were 41 occurrences of "shareable" and 2 of "sharable". As they all refer to the concept of shareable configs, I think it would be clearer to use the same form of "shareable" in all occurrences of the word.
Making docs more consistent
N/A
N/A
> docs: sharable -> shareable

- @commitlint/rules/src/signed-off-by.ts
Check for an empty commit message for rule `signed-off-by`.
On a minimal environment with only `commitlint` installed and the `signed-off-by` rule set, writing an empty commit message would result in a runtime exception.
Previously this rule caused a runtime exception trying to validate an empty commit message as it was trying to access the `startsWith` string method on an undefined value which was supposed to store the last line of the commit message. Now it does a check to see if the last line is `undefined` or not.
> fix(rules): handle blank commit message in `signed-off-by` rule

- @alias/commitlint/cli.test.js
- @alias/commitlint/package.json
- @commitlint/cli/package.json
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
- @commitlint/prompt-cli/cli.js
- @commitlint/prompt-cli/cli.test.js
- @commitlint/prompt-cli/package.json
- @commitlint/read/package.json
- @commitlint/read/src/read.test.ts
- @commitlint/read/src/read.ts
- @commitlint/rules/package.json
- @commitlint/rules/src/trailer-exists.ts
- @commitlint/travis-cli/package.json
- @commitlint/travis-cli/src/cli.test.ts
- @commitlint/travis-cli/src/cli.ts
- @packages/test/package.json
- @packages/test/src/git.ts
- @packages/utils/dep-check.js
- @packages/utils/package.json
- @packages/utils/pkg-check.js
- yarn.lock
This PR is a suggestion to migrate from [`execa`](https://pkg-size.dev/execa) to a lighter alternative: [`tinyexec`](https://pkg-size.dev/tinyexec).
1. Most usage has been rewritten to use `tinyexec` which provides a wrapper around `child_process`'s `spawn`.
2. The sole usage of `execaSync` has been rewritten to use Node's `child_process.spawnSync` directly as `tinyexec` doesn't provide a wrapper around that. I haven't dug into it very deeply, but I've noticed a ~50% speedup in running `trailer-exists.test.ts`, so that's another gain related to this change.
The migration improves the bundle size and installation time for the project, therefore improving the UX. Most of the advanced `execa` features are unused, and those that are, are simple to rewrite into a blend of `tinyexec` and native …
> chore: replace `execa` with `tinyexec` and Node's `child_process.spawnSync`

- @commitlint/cli/src/cli-error.ts
- @commitlint/cli/src/cli.test.ts
- @commitlint/cli/src/cli.ts
Fixes  #4142 
I wonder if this is a breaking change.
Used 9 after looking at this:
https://www.geeksforgeeks.org/node-js-exit-codes/
Is 9 correct?
~Currently it is not~
Adjusted existing tests
> feat(cli): use special errorCode for missing rules/config #4142

- @commitlint/rules/src/scope-enum.test.ts
- @commitlint/rules/src/scope-enum.ts
Currently, if the scope in message has delimiters(`/`, `,` or `\`), it is considered as multiple scopes and is tested separately.
I add extra checks to see if the scope matches the enum **directly** to allow `'scope-enum'` to have delimiter.
Scope should be able to have delimiter like `/`. And tests should pass when `'scope-enum'` is configured to have delimiter.
```js
rules: {
'scope-enum': [
RuleConfigSeverity.Error,
'always',
[
'foo/bar',
],
],
},
};
```
```sh
echo "fix(foo/bar): qux" | commitlint # fails
⧗   input: fix(foo/bar): qux
✖   scope must be one of [foo/bar] [scope-enum]
```
1. A `multipleSlash` test case is added.
2. Check if adding `foo/bar` to `scope-enum` would work.
> feat: support using delimiter in `scope-enum`

- .github/workflows/container-build.yml
- .github/workflows/docs-deploy.yml
Otherwise they might fail with errors like:
```
Run actions/configure-pages@v5
Error: Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action. Error: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site
Error: HttpError: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site
```
Or:
```
Run docker/login-action@v3
Error: Username and password required
```
> ci: don't run container/deploy jobs in forks

- README.md
`commitlint-config-jira` has been deprecated:
Also, the repository and GitHub user who authored and maintained this project has been deleted:
- [N/A] I have added tests to cover my changes.
- [N/A] All new and existing tests passed.
> docs: remove commitlint-config-jira

- docs/guides/ci-setup.md
Inspired from the GitHub Actions template, this is a yaml template definition that can be used as-is with Azure Pipelines.
Tested and it works like a charm.
This will validate:
* all the commits in a PullRequest
* or the last commit otherwise (pipeline triggered by a push, triggered manually, etc.)
> docs: add azure pipelines CI integration

- @commitlint/is-ignored/src/defaults.ts
In Git 2.43, the double-revert commits have commit messages starting with `Reapply`.
This PR ignores `Reapply` commits by default.
https://github.blog/open-source/git/highlights-from-git-2-43/#split-repositories-with-object-filters:~:text=HEAD%20%2D%3E%20main)-,Reapply,-%22fix%20bug%22
> feat(is-ignored): ignore reapply commits

- Dockerfile.ci
This reduces the container image size from about 950MB to 200MB.
Closes #4183.
See #4183
```shell
$ docker buildx build -f Dockerfile.ci .
```
Although I've labeled this as a non-breaking change, it could potentially disrupt containers derived from this image. Please consider reclassifying it as a breaking change if necessary.
> feat(container): switch to Alpine container

- Dockerfile.ci
Install git in container.
git is not copied from the builder layer to the final layer, so we have to install it again.
With the switch to Alpine in #4185, `--from-last-tag` (and possibly other arguments relying on git) no longer works. 
This is because git is no longer available in the container.
See #4196 
Tested locally by using the new image in combinat
> build: fix install git in container

- docs/guides/getting-started.md
- docs/guides/local-setup.md
Add docs for [Deno](https://deno.com).
> docs: add setup guide for deno

- docs/guides/ci-setup.md
The current documentation suggests using `HEAD~n` to go through all PR commits where `n` is the number of commits in the PR. This may not always produce the desired result though, especially if the history is not perfectly linear and there is a complex history of merges.
GitHub Actions provides the base sha on the `pull_request` object as well. This should give a revision list in line with the git log and revisions shown on GitHub.
While using the previous CI workflow, I found that the commits being linted where different from those I was seeing in the PR. After reading a bit about how `~` and `^` work with git I came to the conclusion that going `~n` will not necessarily point to the same revision as the first commit shown in the PR (merge base), especially if the history is complex. …
> docs: use GH base sha to lint PR commits

- docs/guides/local-setup.md
Windows users should use ` to escape dollar signs.
Windows users should use ` to escape dollar signs, so I add one more command in the Local Setup section.
Windows users should use ` to escape dollar signs. The original command below will get wrong outpt
```  shell
echo "deno task --eval commitlint --edit \$1" > .husky/commit-msg
deno task --eval commitlint --edit \
echo "deno task --eval commitlint --edit `$1" > .husky/commit-msg
deno task --eval commitlint --edit $1
```
Related discuss in StackOverflow: https://stackoverflow.com/questions/17452401/escaping-dollar-signs-in-powershell-path-is-not-working
> docs: use ` to escape dollar signs in Windows

- @commitlint/config-lerna-scopes/package.json
`@commitlint/config-lerna-scopes` works fine with the latest versions of lerna. Thanks to [the production dependency](https://github.com/conventional-changelog/commitlint/blob/d2f33c634c88ff6e578e0c9fe96a1517c412e24e/%40commitlint/config-lerna-scopes/package.json#L42-L43) it doesn't actually need a peer version of lerna at runtime. But we do need to be sure that using `@lerna/project@6` continues to work with the latest lerna setup. I can confirm that it does, and this PR just formalizes compatibility.
Declaring compatibility removes peer dependency noise from package managers like yarn and pnpm when using this shared config with the latest versions of lerna.
```sh
pnpm add -D lerna @commitlint/config-lerna-scopes
```
We've been tolerating the peer dependency warning and using this shared …
> feat: support lerna 7 and 8

- @commitlint/config-nx-scopes/index.js
This PR remove the filter projects by targets property
Currently the targets property is not always explicitly defined, now most of the task are inferred using Crystal.
N/A
```js
import { utils } from '@commitlint/config-nx-scopes';
extends: ['@commitlint/config-conventional', '@commitlint/config-nx-scopes'],
rules: {
'scope-enum': async (ctx) => [2, 'always', ['repo', 'deps', 'release', ...(await utils.getProjects(ctx))]],
},
};
```
```sh
```
In my own Nx 20.4.0 workspace, where next apps are created without the targets property and the project is ignored by the plugin unless I remove the line removed in this PR
> fix(config-nx-scopes): fix for projects without explicit targets

- @commitlint/is-ignored/src/is-ignored.test.ts
- @commitlint/is-ignored/src/is-ignored.ts
- @commitlint/is-ignored/src/validate-ignore-func.ts
This PR improves security validation in the `@commitlint/is-ignored` package by introducing a regex pattern to catch potentially malicious function calls.
The current security validation in `is-ignored` only performs type validation on the Matcher, this PR adds a more strict check and throws if the function does not returns a Boolean, plus it checks for potentially dangerous side effects (e.g., `fetch("url")`) that could potentially allow malicious code to be executed through custom ignore functions.
```js
ignores: [
// This will now be caught as potentially dangerous
commit => {
fetch("https://evil.com");
return true;
},
// This remains valid
commit => commit.includes("fetch")
]
};
```
- Added new test cases for various malicious patterns in …
> fix(is-ignored): introduce security validation for custom ignore functions

- docs/guides/ci-setup.md
This PR improves the documentation examples of the GitLab CI pipeline job script so that commitlint checks all commits on a merge request instead of just the last.
The GitLab CI pipeline job scripts in the documentation examples only check the last commit of a merge request, if it has several commits.
This PR changes the documentation examples so that commitlint checks all commits on a merge request.
Not applicable.
I tested the example GitLab Ci pipeline job script on a GitLab instance by opening a merge request with more than one commit.
The CI pipeline job script checked all commits of the merge request (not just the last).
> docs: improve GitLab CI pipeline job script

- @commitlint/config-workspace-scopes/fixtures/basic/@packages/a/package.json
- @commitlint/config-workspace-scopes/fixtures/basic/@packages/b/package.json
- @commitlint/config-workspace-scopes/fixtures/basic/package.json
- @commitlint/config-workspace-scopes/fixtures/empty/package.json
- @commitlint/config-workspace-scopes/fixtures/nested-workspaces/@packages/a/nested-a/package.json
- @commitlint/config-workspace-scopes/fixtures/nested-workspaces/@packages/b/nested-b/package.json
- @commitlint/config-workspace-scopes/fixtures/nested-workspaces/package.json
- @commitlint/config-workspace-scopes/fixtures/scoped/@packages/a/package.json
- @commitlint/config-workspace-scopes/fixtures/scoped/@packages/b/package.json
- @commitlint/config-workspace-scopes/fixtures/scoped/lerna.json
- @commitlint/config-workspace-scopes/fixtures/scoped/package.json
- @commitlint/config-workspace-scopes/index.js
- @commitlint/config-workspace-scopes/index.test.js
- @commitlint/config-workspace-scopes/license.md
- @commitlint/config-workspace-scopes/package.json
- @commitlint/config-workspace-scopes/readme.md
- package.json
Extract workspaces config into its own package.
Set the NPM constraint to 7+ as v7 introduced workspaces.
Please see the long explanation in https://github.com/conventional-changelog/commitlint/issues/4262
```js
extends: ['@commitlint/config-workspace-scopes']
};
```
```sh
echo "feat(nonexisting-pkg): your commit message here" | commitlint # fails
echo "feat(existing-pkg): your commit message here" | commitlint # passes
```
Local test suite in the project based on the current lerna implementation
> feat(config-workspace-scopes): add config preset for npm and yarn workspaces

- @commitlint/cli/index.cjs
- @commitlint/cz-commitlint/index.cjs
- @commitlint/load/fixtures/basic-config/.commitlintrc.cjs
- @commitlint/load/fixtures/basic-config/commitlint.config.cjs
- @commitlint/load/fixtures/extends-config/.commitlintrc.cjs
- @commitlint/load/fixtures/extends-config/commitlint.config.cjs
Closes #4300
See linked issue.
N/A 
Ran existing tests.
> chore: add missing `'use strict'` directives

- @commitlint/rules/src/header-trim.ts
Optimizes header-trim rule to perform better. Comparing a string to another string is an unnecessary cost in this case.
I also replaced the `switch/case` with plain `if`s, which are simpler.
I just happened to see the code, and noticed it could be improved.
N/A
Existing tests pass.
> perf(rules): optimize header-trim

- docs/guides/getting-started.md
- docs/guides/use-prompt.md
- docs/reference/examples.md
Resolves #4381 which displayed commands not compatible across different Operating Systems.
SImplification of data displayed to the reader (better UX/DX) and consistency across operating systems.
This has been tested by running a sample o fthe documentation in local environment.
> docs: adjust package managers CLI instructions for both Win and Unix based systems (#4381)

- docs/guides/getting-started.md
Since Bun is becoming a relevant player within JS runtimes and package managers, it'd be nice to complement the documentation with CLI instructions using that as well (resolves #4380).
Bun is a new byt very relevant package manager lready. There are many developers alrady adopting it as primary run time or at least as their package manager, since it has been showing great performance and developer experience.
This has been tested by running a sample o fthe documentation in local environment.
> docs: add CLI instruction for Bun package manager (#4380)

- README.md
Add documentation explaining how to work around a config loading bug introduced by Node 24.
Fixes https://github.com/conventional-changelog/commitlint/issues/4399 
N/A, docs only
N/A, docs only
> docs: add a note about configuration under node24

- .github/workflows/CI.yml
This PR expands the GitHub Actions CI build strategy by updating the OS matrix in the workflow YAML to include two new target operating system versions.
| Change | Details | Files |
| ------ | ------- | ----- |
| Expanded the OS matrix in the CI build job | <ul><li>Added ubuntu-24.04 to the matrix</li><li>Added windows-2025 to the matrix</li></ul> | `.github/workflows/CI.yml` |
This pull request is needed because it updates the CI (Continuous Integration) matrix to include support for Ubuntu 24.04 and Windows 2025. By adding these environments, the repository ensures that its code is tested and verified to work on the latest operating systems, which improves compatibility and future-proofs the project.
My forked repo.
> chore: add Ubuntu 24.04 and Windows 2025 to CI

- .github/workflows/CI.yml
- .github/workflows/container-build.yml
- .github/workflows/docs-deploy.yml
Most first-party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes, but this is not available for third-party actions yet.
N/A
N/A
> ci: use tags for immutable github actions

- .github/workflows/commitlint.yml
This PR adds a new GitHub Actions workflow that enforces Conventional Commit message conventions by installing dependencies, building the code, and validating commits on pushes, pull requests, and manual triggers.
<details>
<summary>File-Level Changes</summary>
| Change | Details | Files |
| ------ | ------- | ----- |
| Define a new commitlint workflow with triggers and permissions | <ul><li>Create .github/workflows/commitlint.yml</li><li>Configure triggers for push, pull_request, and workflow_dispatch</li><li>Grant read access to repository contents</li></ul> | `.github/workflows/commitlint.yml` |
| Set up environment and build steps | <ul><li>Checkout repository with full history (fetch-depth: 0)</li><li>Install Node via actions/setup-node with yarn caching</li><li>Run yarn install and …
> ci: add commitlint GitHub Actions

- docs/guides/local-setup.md
Documentation:
- Add missing `--` flag to the npx commitlint command in the husky commit-msg hook example in the local-setup guide
```sh
npm install --save-dev husky
npx husky install
echo "npx --no -- commitlint --edit \$1" > .husky/commit-msg
echo "npx --no -- commitlint --edit `$1" > .husky/commit-msg
```
As an alternative you can create a script inside `package.json`
```sh
npm pkg set scripts.commitlint="commitlint --edit"
echo "npm run commitlint \${1}" > .husky/commit-msg
```
I have tested on my local PC.
> docs: add missing double hyphen to npm husky command in setup guide

- docs/guides/local-setup.md
Add a new ‘bun’ section to the local setup guide for installing Husky and configuring a commitlint hook
Documentation:
- Introduce a ‘bun’ guide showing how to install Husky and initialize its hooks
- Show how to add a commitlint hook with bunx, including a Windows-specific command variation
#4383 added CLI instruction for Bun package manager.
However, [the setup guide](https://commitlint.js.org/guides/local-setup.html#using-a-git-hooks-manager) didn't updated.
```sh
bun add --dev husky
bunx husky install
echo "bunx commitlint --edit \$1" > .husky/commit-msg
echo "bunx commitlint --edit `$1" > .husky/commit-msg
```
I have tested on my local PC.
> docs: add setup guide for bun

- .devcontainer/devcontainer.json
Enhancements:
- Move VSCode extensions specification to the customizations.vscode.extensions section in .devcontainer/devcontainer.json
Property `extensions` is not allowed in [the latest devcontainer.json](https://containers.dev/implementors/json_reference/#general-properties).
Then use [`customizations/vscode/extensions`](https://containers.dev/supporting#visual-studio-code) instead.
```json
{
"name": "commitlint-dev",
"dockerComposeFile": ["../docker-compose.yml"],
"service": "commitlint",
"workspaceFolder": "/root/repo",
"shutdownAction": "stopCompose",
"customizations": {
"vscode": {
"extensions": [
"editorconfig.editorconfig",
"esbenp.prettier-vscode",
"ms-azuretools.vscode-docker",
"ms-vsliveshare.vsliveshare-pack"
]
}
}
}
```
I have tested it with GitHub Codespaces.
> chore: use customizations/vscode/extensions instead of extensions property

- docker-compose.yml
Build:
- Update docker-compose.yml to Docker Compose v2 syntax and convert environment variables to key-value format
The top-level `version` property is defined by the Compose Specification for backward compatibility. It is only informative and you'll receive a warning message that it is obsolete if used.
```diff
- SSH_AUTH_SOCK=/.ssh-agent/socket
+ SSH_AUTH_SOCK: /.ssh-agent/socket
```
The new `FOO: BAR` mapping syntax is prefer to `- FOO=BAR` sequence syntax at 2 points.
First mapping syntax can use [Fragments](https://docs.docker.com/reference/compose-file/fragments/).
```yaml
services:
first:
image: my-image:latest
environment: &env
FOO: BAR
ZOT: QUIX
second:
image: another-image:latest
environment:
<<: *env
YET_ANOTHER: VARIABLE
```
> In [example …
> chore: update docker-compose.yml to v2

- docs/reference/cli.md
Integrate dynamic version display for the commitlint CLI in the reference docs and adjust the code block syntax
Documentation:
- Import the CLI’s package.json in a Vue script setup to inject the current version into the docs
- Update the CLI example code fence from `sh` to `sh-vue` and replace the hardcoded version with the dynamic value
I got the below review.
> I don't think this requires to be updated for every single release, or we should have a automation tool to do this.
Then implement that.
```sh
npx commitlint --help
```
```sh
yarn docs-build
yarn docs-preview
```
> docs: version up @commitlint/cli in CLI section

- docs/guides/local-setup.md
- docs/guides/use-prompt.md
Group shell command examples into code-group blocks and add Yarn, pnpm, Bun, and Deno variants across the use-prompt and local-setup guides.
Documentation:
- Wrap initialization, installation, commit, and linting commands in code-group sections for npm, Yarn, pnpm, Bun, and Deno in use-prompt.md
- Add corresponding code-group examples for running commitlint and testing hooks in local-setup.md with npm, Yarn, pnpm, Bun, and Deno
I hope these changes will help other developers that use yarn, pnpm, bun and deno easily set up commitlint.
```sh [npm]
npx commitlint --from HEAD~1 --to HEAD --verbose
```
```sh [yarn]
yarn commitlint --from HEAD~1 --to HEAD --verbose
```
```sh [pnpm]
pnpm dlx commitlint --from HEAD~1 --to HEAD --verbose
```
```sh [bun]
bunx commitlint --from HEAD~1 --to HEAD …
```
> docs: add multi JavaScript package manager and code groups to guides

- docs/reference/configuration.md
Update documentation to reference cosmiconfig v9.0.0 instead of v8.2.0
According to [@commitlint/load CHANGELOG.md](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/load/CHANGELOG.md#1920-2024-03-15) ...
> # [19.2.0](https://github.com/conventional-changelog/commitlint/compare/v19.1.0...v19.2.0) (2024-03-15)
>
> ### Features
>
> * **load:** update cosmiconfig to v9 to add support for `package.yaml` config ([#3976](https://github.com/conventional-changelog/commitlint/issues/3976)) ([94eab40](https://github.com/conventional-changelog/commitlint/commit/94eab40798e0c8d3945aa2b1e629669b231d8468))
Therefore, I updated the cosmiconfig link.
N/A
N/A
> docs: update cosmiconfig url to v9.0.0

- docs/guides/local-setup.md
Update commitlint invocation instructions in the local setup guide
Documentation:
- Use 'pnpm commitlint' instead of 'pnpm dlx commitlint' in the pnpm example
- Use 'bun commitlint' instead of 'bunx commitlint' in the bun example
Follow up #4501
Simplified the commitlint commands in the local setup guide by removing auxiliary wrappers (dlx, bunx) and relying on the direct package manager invocations.
> docs: update commitlint test code

- @commitlint/ensure/src/max-line-length.ts
- @commitlint/rules/src/body-max-line-length.test.ts
- docs/reference/rules.md
Whilst the `body-max-line-length` is almost always desirable, there is one fairly frequent scenario in which it gets in the way: when lines in the body of the commit message contain URLs exceeding the maximum line length.
In this case, the URL cannot be split across lines without breaking it, and minifying it results in obfuscation and a dependency on a third-party service, both of which are undesirable.
So make an exception in this rule for any line which contains a URL.  Allow other content on the same line, in order to support use of various rich-text formats such as Markdown, which are often used in order to render links in more elegant ways.
After lengthy discussion in #2112 of how to handle long URLs, this PR proposes a simple fix which seems to be closest to achieving broad …
> feat(rules): make body-max-line-length ignore lines with URLs

- @commitlint/config-pnpm-scopes/index.test.ts
- @commitlint/config-pnpm-scopes/index.ts
- Deduplicate resolved workspace package names and always include a `global` scope.
- Align the `@commitlint/config-pnpm-scopes` tests with the new `global` scope expectation.
When using a pnpm workspace, it’s not possible to specify a scope for file changes made directly under the root.
I used pnpm add --global as a reference and named the scope global.
https://pnpm.io/ja/cli/add#--global--g
The pnpm workspace root often needs commits that touch shared files. Without a shared scope option, commitlint rejects those messages. Adding `global` keeps the restriction for packages while enabling root-level changes.
```js
extends: ["@commitlint/config-pnpm-scopes"],
};
```
```sh
echo "chore(global): update pnpm-workspace.yaml" | commitlint
```
- `pnpm …
> feat(config-pnpm-scopes): allow global scope
