conventional-changelog/commitlint

.conventional-changelog-lintrc
.npmrc
.travis.yml
package.json
scripts/lint-prcommits.sh

* introduce linting of all commits in a PR
* handle PRs from clones properly
* showcase for #35 and #12

chore: test commits in pr via Travis CI

---

readme.md
scripts/lint:commits.sh

* be more explicit / guide more than #24
* closes #35
* connected to #12

docs: add recipe for linting of all commits in a PR

---

@commitlint/cli/cli.js
@commitlint/core/fixtures/parser-preset/commitlint.config.js
@commitlint/core/fixtures/parser-preset/conventional-changelog-custom.js
@commitlint/core/fixtures/recursive-parser-preset/commitlint.config.js
@commitlint/core/fixtures/recursive-parser-preset/first-extended/index.js
@commitlint/core/fixtures/recursive-parser-preset/first-extended/second-extended/conventional-changelog-custom.js
@commitlint/core/fixtures/recursive-parser-preset/first-extended/second-extended/index.js
@commitlint/core/src/library/parse.js
@commitlint/core/src/library/parse.test.js
@commitlint/core/src/library/resolve-extends.js
@commitlint/core/src/lint.js
@commitlint/core/src/lint.test.js
@commitlint/core/src/load.js
@commitlint/core/src/load.test.js
appveyor.yml

feat: add preset parser

---

docs/guides-ci-setup.md

Follow install script in [README](https://github.com/marionebl/commitlint#readme).

docs: fix incorrect package names to install

---

.gitignore
@commitlint/core/src/library/ensure-case.js
@commitlint/core/src/rules/scope-case.test.js
@commitlint/core/src/rules/subject-case.test.js
@commitlint/core/src/rules/type-case.test.js
docs/reference-rules.md
package.json

Builds on https://github.com/marionebl/commitlint/pull/72

feat(core): add additional case options

---

@commitlint/cli/fixtures/inner-scope/commitlint.config.js
@commitlint/cli/fixtures/inner-scope/inner-scope/commitlint.config.js
@commitlint/cli/fixtures/outer-scope/commitlint.config.js
@commitlint/cli/src/cli.test.js
@commitlint/core/fixtures/outer-scope/commitlint.config.js
@commitlint/core/fixtures/outer-scope/inner-scope/child-scope/commitlint.config.js
@commitlint/core/src/load.js
@commitlint/core/src/load.test.js
@packages/test/src/fix.js
@packages/test/src/git.js
@packages/test/src/index.js

fix(core): consider config outside of current git repo

---

@commitlint/core/package.json
@commitlint/core/src/library/parse.js
@commitlint/core/src/library/parse.test.js
yarn.lock

* switch to patched fork of conventional-commits-parser
* add test cases for comments
* fixes #78

fix(core): ignore comments

---

@commitlint/core/src/rules/subject-case.js

* towards support for #114
```js
'subject-case': [2, 'never', ['sentence-case', 'pascal-case', 'start-case', 'upper-case']]
}
```

feat(core): expose fine-grained API for subject-case

---

@commitlint/prompt/src/settings.js

feat(prompt): add description for build and ci

---

@commitlint/config-conventional/index.js

Adds missing `applicablity` attribute to the `type-enum` rule.
Resolves
```
TypeError: Cannot read property 'join' of undefined
at exports.default (.../node_modules/@commitlint/core/lib/rules/type-enum.js:28:119)
at .../node_modules/@commitlint/core/lib/lint.js:72:18
at Array.map (<anonymous>)
at Object.<anonymous> .../node_modules/@commitlint/core/lib/lint.js:53:8)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
```js
"extends": ["@commitlint/config-conventional"]
};
```
```sh
```
now warns instead of fatally crashing

fix(config-conventional): add missing applicable attribute to type-enum

---

README.md

Add a link to [create-semantic-module](https://github.com/jlegrone/create-semantic-module) in the related projects section of the readme
I wrote `create-semantic-module` to add conventional commit tooling to projects with minimal fuss.  
Hopefully this tool will set others up for success introducing conventional commits!

docs: add create-semantic-module to related projects

---

@packages/babel-preset-commitlint/index.js
@packages/babel-preset-commitlint/package.json
yarn.lock

JSX transform is needed to enable ink as CLI tool.
Plugin and plugin options are recommended by ink as part of the package setup process.
<https://github.com/vadimdemedes/ink#getting-started>
first step toward #86
Existing unit tests.

feat(babel-preset-commitlint): add jsx tranform

---

@commitlint/travis-cli/src/cli.test.js

Disable some tests that were marked as failing anyway

ci: fix appveyor runs

---

docs/guides-ci-setup.md

docs(travis-yml): fix typo

---

docs/guides-ci-setup.md

Hi, I found a bit typo in documentation. Please check it 😃 🙏 
Fixed a bit typo in shell script example for Travis CI. In [this page](http://marionebl.github.io/commitlint/#/guides-ci-setup?id=linting-relevant-commits).
Motivation  for correct documentation.
n/a
n/a

docs: fix typo

---

@commitlint/travis-cli/src/cli.js
@commitlint/travis-cli/src/cli.test.js

Correct minor typo in travis-cli when not being executed in the Travis CI environment.
No reason really, other than to resolve a pedantic niggle.
N/A
N/A
`npm test`

docs(travis-cli): correct spelling of intended

---

@commitlint/ensure/src/case.js
@commitlint/ensure/src/case.test.js
yarn.lock

#290 
```js
rules: {
'scope-case': [2, 'always', 'camel-case'],
'scope-enum': ['*']
}
};
```
```sh
echo "feat(*): subject" | commitlint # passes
```

fix(ensure): ignore word delimiters for case matching #291

---

@commitlint/prompt/README.md

docs: use `--save-dev` to align with main project

---

.gitignore
@commitlint/is-ignored/src/index.js

I'm trying to close issue [315](https://github.com/marionebl/commitlint/issues/315), as well as add my another pattern which I encountered.
Please let me know there is something i can do better with this PR :)
Side-note: I think those patterns should be user-configurable, not hardcoded

feat(wildcards): add new wildcard patterns (#315)

---

docs/concepts-shareable-config.md

FIx typo in concepts-shareable-config.md
module.expors -> module.exports

Fix typo in concepts-shareable-config.md

---

@commitlint/is-ignored/src/index.js
@commitlint/is-ignored/src/index.test.js

Fixes #417 
I've added a test case which should return false according to the issue description.

fix(is-ignored): use grouped regex to ignore merge commits

---

README.md

Spent an hour figuring out how to publish my own shared configuration. Thought this doc addition would help others.

 📖 DOC: Instructions for shared configs

---

docs/concepts-commit-conventions.md

fix spelling Aumomatic -> Automatic

---

@commitlint/resolve-extends/src/index.js
@commitlint/resolve-extends/src/index.test.js

On resolving extends we analize that value is array and override him (https://github.com/marionebl/commitlint/issues/470)
With the help of tests and by putting the package in project example

fix(resolve-extends): override array on extending rules (#470)

---

@commitlint/resolve-extends/package.json
@commitlint/resolve-extends/src/index.js
yarn.lock

This fixes #515
Old or deprecated libraries often tend to not have any updates. I'd figure we should update too.

chore: replace require-uncached with import-fresh

---

@packages/utils/pkg-check.js

Fix for the issue described in #549

fix(utils): store concatenated array to problems variable

---

@commitlint/parse/src/index.js

It's a small but proper change.

fix(parse): mark optional parameter with undefined

---

@commitlint/prompt-cli/cli.js
@commitlint/prompt-cli/package.json
yarn.lock

This fixes #550.
I have fully removed `meow` from the prompt-cli dependency too, and rebuilt the lock file. Might be worth checking if that went well, I think it did.

Fix unexpected parameter in `@commitlint/prompt-cli`

---

README.md

This was using the good ol' rawgit.com, now we can use relative paths (thanks for the tip 😄)

refactor: use relative svg path in readme

---

@commitlint/cli/README.md
@commitlint/config-angular/README.md
@commitlint/config-conventional/README.md
@commitlint/config-lerna-scopes/readme.md
@commitlint/config-patternplate/README.md
@commitlint/format/README.md
@commitlint/lint/README.md
@commitlint/load/README.md
@commitlint/prompt-cli/README.md
@commitlint/prompt/README.md
@commitlint/read/README.md
README.md

The final batch of reference-updates!

fix: replace all website references with conventional changelog

---

@commitlint/cli/src/cli.js

fix(cli): replace old links with new organisation links

---

docs/reference-api.md

docs(format): update api to match function arguments

---

package.json

This should fix our husky issue during commit-hooks.
Short summary of the _option 2_-fix from my spam-messages in slack:
> The way I see it, we can fix it by one of these options:
> 
> 1. Move `@lerna/project` over to `dependencies` (not dev-) to have it installed in whatever package its using, in our case the root of commitlint (not commitlint packages).
> 2. Include the `@lerna/project` in the root of commitlint (not commitlint packages) to have it installed there, and be available to all of this.
> 
> There might also be a solution to change the provided working directory, but I tend to not-change the behaviour of the package because it looks like an issue with our repo only.

fix: add @lerna/project to repository dependencies

---

@commitlint/load/package.json
@commitlint/load/src/index.js
package.json
yarn.lock

Trying to update cosmiconfig. But failing.
Getting this for all tests:
```bash
Rejected promise returned by test. Reason:
Error {
code: 'EISDIR',
errno: -21,
syscall: 'read',
message: 'EISDIR: illegal operation on a directory, read',
}
```
I played around with it and tried other options. I'm lost...
```js
};
```
```sh
```

WIP: Fix/599 js yaml cosmiconfig

---

Dockerfile
docker-compose.yml

```
docker-compose pull
docker-compose up
```

chore: add turnkey dev setup

---

@commitlint/is-ignored/index.d.ts

replaced double quotes with single quotes wrapping a string in `@commitlint/is-ignored` to conform with prettier configuration
resolves linting error blocking build on master.
`npm lint` passes.

style(is-ignored): update quotes to conform with prettier config

---

@commitlint/top-level/src/index.ts

fix prettier formatting on top-level/index.ts

---

package.json

Upgrade lodash to 4.17.14
A security vulnerability is reported by WhiteSource: "A Prototype Pollution vulnerability was found in lodash through version 4.17.11." It is recommended to upgrade to the latest version.
The current release has a lodash dependency set to a fixed version. This version of lodash has a high severity of security vulnerability. lodash should be updated to fix the reported vulnerability.
CVE-2019-10744
More information
high severity
Vulnerable versions: < 4.17.13
Patched version: 4.17.13
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
- yarn install
- ran tests

chore: update dependency lodash to 4.17.14

---

docs/guides-local-setup.md

docs: add simple setup test #775

---

@alias/commitlint-config-angular/README.md
@alias/commitlint-config-lerna-scopes/README.md
@alias/commitlint-config-patternplate/README.md
@alias/commitlint/README.md

docs: update alias links #776

---

README.md

Update minimum git version to reflect huskys dependency.  
See #782 for context.

docs: update version support for git due to husky #782

---

README.md

Add commitlint-config-jira to shared configurations list 
commitlint-config-jira is part of [commitlint-jira](https://github.com/Gherciu/commitlint-jira) monorepo, that include a shared config, a plugin and utils to lint JIRA style commit messages.
- Most companies use JIRA as a task tracker
- To track what task is resolved in a commit
- To have a single commit message style for the entire team
```
npm install --save-dev @commitlint/cli commitlint-plugin-jira-rules commitlint-config-jira
```
```js
plugins: ['commitlint-plugin-jira-rules'],
extends: ['commitlint-config-jira'],
}
```
```sh
echo "IB-2121: my commit message" | commitlint # passes
echo "IB-2121, IB-0000: my commit message" | commitlint # passes
echo ": my bad commit message" …
```

chore: add commitlint-config-jira to shared configurations list

---

@commitlint/config-conventional/index.js

Fixes https://github.com/commitizen/cz-cli/issues/681
Ref: https://github.com/commitizen/conventional-commit-types/commit/d8496659dd001f7212d0c209a49a824da15de3e6

Add improvement to allowed list.

---

@commitlint/is-ignored/package.json

This should not be included in the published library.

fix(is-ignored): move types to dev dependencies

---

.circleci/config.yml
package.json

This prevents `ts-jest` to flood the memory, making it horrible slow and often failing without memory

test: run jest in band on circle ci

---

@commitlint/config-conventional/README.md
@commitlint/config-conventional/index.js

chore(config-conventional): increase header-max-length to 100

---

@commitlint/prompt/package.json
@commitlint/prompt/src/library/get-prompt.test.js
jest.config.js

migrate prompt tests from ava to jest
There is nothing to note in those tests
Unrelated

test(prompt): migrate ava tests to jest

---

@commitlint/lint/package.json
@commitlint/load/package.json
yarn.lock

Cleanup dev dependencies after changes from #922 and #786
Unrelated

chore: remove unused dev dependencies

---

@commitlint/cli/package.json
@commitlint/config-patternplate/package.json
@commitlint/ensure/package.json
@commitlint/lint/package.json
@commitlint/load/package.json
@commitlint/parse/package.json
@commitlint/prompt/package.json
@commitlint/resolve-extends/package.json
@commitlint/rules/package.json
@packages/utils/package.json

Add caret to lodash versions to prevent having to bump versions just to update lodash. Fix #840 
Running the `build` and `test` commands against master and my branch.

fix: #840 add caret to lodash versions

---

package.json
yarn.lock

Supersedes #870. Had some trouble getting the install to work while rebasing, so went with this instead. Thanks @L2jLiga

chore: update docsify

---

@packages/test/src/npm.ts

Fix tests on windows machines #954
Manual test run

fix(test): tests on windows machines

---

.circleci/config.yml

Reenable windows testing to catch things like #955

ci: trial testing on windows

---

@commitlint/parse/src/index.test.ts

test(parse): fix not awaited parse tests

---

README.md

update node version support to `>= 8` in readme

docs: update supported node version in readme

---

@commitlint/ensure/package.json
yarn.lock

align required globby between packages
https://github.com/conventional-changelog/commitlint/blob/f379dcc36948a5ec2dfec9bcd0f47ffe8fdaff6c/%40commitlint/ensure/package.json#L38-L40
https://github.com/conventional-changelog/commitlint/blob/f379dcc36948a5ec2dfec9bcd0f47ffe8fdaff6c/%40commitlint/rules/package.json#L40-L42
https://github.com/conventional-changelog/commitlint/blob/f379dcc36948a5ec2dfec9bcd0f47ffe8fdaff6c/%40commitlint/config-patternplate/package.json#L32-L34

chore(ensure): align required globby between packages

---

@commitlint/cli/package.json
@commitlint/prompt/package.json
@commitlint/travis-cli/package.json
yarn.lock

Add missing dep to solve #1738

fix: add missing @babel/runtime dep #1738

---

README.md
docs/_sidebar.md
docs/reference-community-projects.md

Adding community-project section.

docs: community projects

---

@commitlint/load/fixtures/extends-with-local-plugins/commitlint.config.js
@commitlint/load/fixtures/extends-with-local-plugins/config-with-local-plugin/commitlint.config.js
@commitlint/load/fixtures/extends-with-local-plugins/config-with-local-plugin/index.js
@commitlint/load/fixtures/extends-with-plugins/commitlint.config.js
@commitlint/load/fixtures/extends-with-plugins/config-with-plugins/commitlint.config.js
@commitlint/load/fixtures/extends-with-plugins/config-with-plugins/index.js
@commitlint/load/src/load.test.ts
@commitlint/load/src/load.ts

fix(load): resolve plugins from extended configs

---

docs/reference-rules.md

add missed tip for *-case in reference-rules
Just discover some mistake when explore document

docs: add missed tip for *-case in reference-rules

---

package.json

Drop `v` prefix from node's version in package.json
Some tools (e.g. voltajs) does not recognize the node version format.
N/A

Specify correct node version format in package.json

---

README.md

See this [PR](https://github.com/typicode/husky/pull/832) in husky's repo.

docs: `pre-commit` -> `commit-msg` for Husky v5

---

docs/guides-upgrade.md

docs: update incorrect slack link

---

@commitlint/ensure/jest.config.js
@commitlint/execute-rule/jest.config.js
@commitlint/format/jest.config.js
@commitlint/resolve-extends/jest.config.js
@commitlint/to-lines/jest.config.js

Removal of left over files from migration of codebase to typescript

chore: remove unused jest configs

---

@commitlint/cli/src/cli.test.ts

This should ease release process by replacing version check with more stable code
Avoid unnecessary changes required during release e564a1e30782f03b34ae2d5fcc7322bdba18c0e3
unit tests

test(cli): update version check for help test

---

@commitlint/rules/src/index.test.ts
docs/reference-rules.md

correct documentation for rules
- missing docs for rules:
- body-case
- footer-empty
- body-empty
- add simple unit test for docs validation
- update lowerCase to lower-case
fixes #875
new unit test has been added

docs: add missing rules to documentation

---

@commitlint/cli/package.json
@commitlint/cli/src/cli.ts
@commitlint/cli/src/types.ts
@packages/utils/package.json
yarn.lock

this dependency upgrade requires some special treatment as #2430 is failing

chore: update dependency @types/yargs to v16 and yargs to v16.2

---

docs/guides-local-setup.md

style(guides-local-setup): Fix a typo

---

@commitlint/config-conventional/README.md

These don't take a value.
```js
```
```sh
```

docs(config-conventional): remove spurious body-leading-blank and footer-leading-blank values

---

README.md
docs/guides-local-setup.md

A new version of husky has been published which should make adding a command to a hook simpler :)
Starting with husky 5.2.0, `husky add ...` will now append command or create a new file

docs: update getting started

---

@commitlint/config-conventional/index.js
@commitlint/config-conventional/index.test.js

Please see #828 for further details – This is the rebased version of that PR.

Allow any scope casing for Conventional Commits

---

README.md
docs/guides-local-setup.md

Quick readme update on Husky v6. 
closes #2553

Update readme about husky update

---

package.json
yarn.lock

chore: update docsify-cli

---

README.md

See #2637 for more detail 
```js
```
```sh
```

docs: yarn v2 is now supported

---

@commitlint/config-conventional/README.md

remove semicolon where not necessary in the docs
remove semicolon where not necessary in the docs
N/A
N/A

docs: remove semicolon where not necessary

---

README.md
docs/guides-local-setup.md

> [If you have time, please create a PR to update the docs](https://github.com/conventional-changelog/commitlint/pull/83#issuecomment-903100520)

docs: add missing alternative cfg file names

---

@commitlint/prompt/package.json
yarn.lock

Align versions of packages after PR #2697 merge

fix(prompt): correct version of internal dependencies in prompt package 

---

README.md

Same as https://github.com/conventional-changelog/commitlint/pull/2490.

docs(readme): sort commit type list

---

@commitlint/load/package.json
@commitlint/load/src/utils/load-config.ts
yarn.lock

chore(load): switch to official cosmiconfig-typescript-loader #2912

---

docs/reference-rules.md

`condition: header is in case value` changed to `condition: body is in case value`.

docs: body-case updated #2919

---

@commitlint/config-angular/README.md

docs: fix typo in config-angular README

---

docs/guides-ci-setup.md

Resolves #3083
```js
module.exports = {}; // default
```
```sh
echo "fix: update dependencies
- package 1
- package 2
" | npx commitlint # fails (warning)
```

docs: use correct variable in Gitlab CI example (#3083)

---

@commitlint/config-angular-type-enum/README.md

docs: fix package name in config-angular-type-enum README

---

docs/guides-local-setup.md

Add x permission to file, otherwise it will not run
without x permission git will not trigger that hook

Add x permiss. to file, otherwise it will not run

---

docs/guides-upgrade.md

docs: fix pkg name in guides-upgrade.md

---

@commitlint/load/package.json

In v3 of `cosmiconfig-typescript-loader`, `ts-node` was removed as dependency and added as peer dependency: https://github.com/Codex-/cosmiconfig-typescript-loader/commit/1c82fdafb5c2601edd789beeb20243c922040ce9
When `@commitlint/load` upgraded to v3 of `cosmiconfig-typescript-loader`, `ts-node` wasn't added as a dependency, but as a peer dependency: https://github.com/conventional-changelog/commitlint/commit/4e87d1431df6d39990e5f56a579604b1b3268ce6
This is a breaking change as it requires `ts-node` to be installed manually. Either `ts-node` should be added as a dependency, or this change should be released as a new major version with a migration guide specifying that `ts-node` now has to be installed manually.
I'd suggest just adding `ts-node` as a direct dependency for now, as it …

fix(load): add ts-node as direct dependency

---

README.md
docs/guides-local-setup.md

Applying the same updates mentioned [here](https://github.com/conventional-changelog/commitlint/pull/3352) to the file `docs/guides-local-setup.md` file.
updated the "commit-msg" hook creation. Fixed `ENOENT: no such file or directory, open` error on pre-commit
Following the docs mentioned [here](https://commitlint.js.org/#/guides-local-setup) I noticed 2 things.
1. The file creation portion doesn't work for me (using macOS Or WSL Ubuntu on Windows)
2. When I create the file manually - the commit-msg hooks gives the error `ENOENT: no such file or directory, open` error on pre-commit`
1. updated the file creation to use echo and the output redirection operator.
2. noticed the error `ENOENT: no such file or directory, open` error on pre-commit` is to do with the sting interpellation. …

docs(docs/guides-local-setup.md): update husky hook file creation

---

README.md
docs/guides-local-setup.md

Fix the docs for local setup.
The local setup does not work for my environment (MacOS/zsh) and this is a more general approach to generating the commit hook.
I already opend issue #3371  for this problem.

fix(docs): let husky create commit hook #3371

---

README.md
docs/guides-local-setup.md

Docs update for the husky hook setup. 
Use single quotes to prevent shells from expanding the variable at hook creation time.
fixes #3387
-
just doc changes
doc changes

docs: fix husky command

---

@commitlint/config-lerna-scopes/package.json

`@commitlint/config-lerna-scopes` uses `@lerna/project` but does not specify it as a dependency.
While https://github.com/conventional-changelog/commitlint/pull/3600 fixed an issue with `@commitlint/config-lerna-scopes` not being compatible with recent Lerna versions, I stumbled upon a second issue after updating both `@commitlint/config-lerna-scopes` and `lerna` to their latest version:
```
Error: Cannot find module '@lerna/project'
Require stack:
- /Users/../noop.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/../node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
at Function.Module._load …
```

fix(config-lerna-scopes): add missing dependency

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR Adds documentation for how to run the test suite to a new "testing" section in the README.
- #3639 
The pull request template asks contributors to confirm that all tests pass. I could not find documentation for how to run the test suite. Turns out the instructions are pretty clearly implied in the README's "Publishing a release" section. I saw that section's heading and, because I'm not trying to publish, skipped right over it. Can imagine others might too.
During development, relevant for contributors making changes which could affect tests and contributors writing tests.
During proposal: all contributors who open pull requests.
I ran the commands listed and confirmed that they ran the test suite.

docs: readme explains how to run tests (resolves #3639)

---

README.md
docs/guides-ci-setup.md
docs/guides-releases.md
docs/reference-api.md
docs/reference-community-projects.md
docs/reference-prompt.md

Correct grammar and typos in the docs.
N/A

docs: correct grammar and typos

---

docs/reference-api.md

docs: typo

---

docs/guides-ci-setup.md

Provide an example (in the form of a step template) of how to
lint commit messages with `commitlint` in a Jenkins X CI/CD 
pipeline.
Read more about Jenkins X here: https://jenkins-x.io/docs/
I have verified that this works on my company Kubernetes cluster.

docs: commitlint with jx3

---

README.md

Just add a required node version badge to the documentation.
```js
```
```sh
```

docs: add node badge

---

@commitlint/config-nx-scopes/index.js

Replace import 
Fixes #3865
N/A
```sh
yarn test
```

fix(config-nx-scopes): replace import with require (#3865)

---

@commitlint/config-nx-scopes/package.json

Add nx 18 support for @commitlint/config-nx-scopes since it's not breaking after the update
Package managers are throwing a warning for unmet peer-dependencies.
@commitlint/config-nx-scopes is still working after updating Nx to v18
This pull request also closes #3895

chore(@commitlint/config-nx-scopes): nx 18 support

---

.codesandbox/ci.json

close #3940
Usage: `yarn add -D https://pkg.csb.dev/conventional-changelog/commitlint/commit/$commit_hash/$package_name`
For instance: `yarn add -D https://pkg.csb.dev/conventional-changelog/commitlint/commit/1b885368/@commitlint/cli`

ci: enable CodeSandbox CI

---

@commitlint/config-angular/index.test.js

remove repetitive word
```js
```
```sh
```

chore: remove repetitive word

---

docs/api/lint.md

The import statement in the api/lint document lacks the from keyword
To better use the documentation.

docs(api/lint): add from keyword

---

docs/guides/local-setup.md

Warn windows users the correct encoding to use.
https://github.com/conventional-changelog/commitlint/issues/4085#issuecomment-2115557857
```js
```
```sh
```

docs: warns about windows correct files encoding

---

docs/.vitepress/config.ts

Link to edit source markdown file from documentation pages.
See https://vitepress.dev/reference/default-theme-edit-link
To [add comments](https://github.com/conventional-changelog/commitlint/issues/4103#issuecomment-2252141144) to the docs.

feat(docs): add edit link

---

docs/guides/ci-setup.md

Add a section in the CI Setup docs to utilize commitlint within a BitBucket pipeline.
I recently implement this at work think it would be useful for other's that are required to work with BitBucket!
```js
```
```sh
```
I implemented this at work and I also previewed the docs locally:

docs: add bitbucket to ci-setup guide

---

@commitlint/config-angular/README.md

Little change
Angular **renamed** `master` branch to `main`!
url change

chore: Update README.md

---

.nxignore

Relates to https://github.com/conventional-changelog/commitlint/pull/4284#issuecomment-2706299233

build: add nx ignore to make lerna publish again

---

@commitlint/config-workspace-scopes/readme.md

docs(config-workspace-scopes): incorrect package name title

---

.github/workflows/CI.yml
.github/workflows/container-build.yml
.github/workflows/docs-deploy.yml

ci: pin github actions to commit-hash

---

package.json
yarn.lock

Reverts conventional-changelog/commitlint#4528

Revert "chore: update dependency cross-env to v10"
